<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
    <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getItemConfigureUrl($item) ?>">
        <span><i class="fa fa-pencil-square-o" aria-hidden="true"></i><?php /* @escapeNotVerified */ echo __(' EDIT') ?></span>
    </a>
<?php endif ?>
