<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<section class="newsletter-home animation-element slide-left">
	<div class="newsletter container">
		<div class="row">
			<div class="title col-md-4 col-xs-12"><strong><?php echo __('Subscribe to our
newsletter') ?></strong></div>
			<div class="content col-md-8 col-xs-12">
				<form class="form subscribe"
					novalidate
					action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
					method="post"
					data-mage-init='{"validation": {"errorClass": "mage-error"}}'
					id="newsletter-validate-detail">
					<div class="field block-newsletter"> 
						<div class="control">
							<input name="email" type="email" id="newsletter"
										placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email') ?>"
										data-validate="{required:true, 'validate-email':true}"/>
						</div>
					</div>
					<div class="actions">
						<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
							<span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
