<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $_helper = $this->helper('Netbase\Sun\Helper\Data');
?>

<a class="title-a">NEWSLETTER</a>
<form class="form subscribe"
    novalidate
    action="<?php echo $block->getFormActionUrl() ?>"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    id="newsletter-validate-detail">
    <div class="field newsletter">
        <div class="control">
            <input name="email" type="email" placeholder="Enter your mail ..." id="footer_newsletter"
                        data-validate="{required:true, 'validate-email':true}"/>
        </div>
    </div>
</form>
