<?php
$helper = $this->helper('Cmsmart\Marketplace\Helper\Data');
$skuType = $helper->getAllowedSkuTypes();
$skuPrefix = $helper->getSkuPrefix();
$product = $block->getProductModel();

$productType = $this->getRequest()->getParam('type');
if (isset($product)) {
    $productId = $product->getId();
}

$arrayCategories = $helper->top_get_categories();
?>

<form action="<?php echo isset($productId)? $this->getUrl("marketplace/product/save/id/$productId") :  $this->getUrl('marketplace/product/save')?>" enctype="multipart/form-data"
      method="post" id="form-customer-product-new">
    <div class="cmsmart-marketplace-field" id="cmsmart-mp-body">
        <div class="page-title">
            <button type="reset" class="action submit primary cmsmart_mp_btn">
                <span><?php echo __('Reset') ?></span>
            </button>
            <button class="action submit primary cmsmart_mp_btn" title="<?php echo __('Save') ?>" type="submit" id="save_butn">
                <span><?php echo __('Save') ?></span>
            </button>
        </div>

        <div class="cmsmart_mp_design">
            <div class="fieldset cmsmart_mp_fieldset">
                <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
                <input type="hidden" name="attribute_set_id" id="attribute_set_id"
                       value="<?php echo $this->getRequest()->getParam('set') != '' ? $this->getRequest()->getParam('set') : 4; ?>"/>
                <input type="hidden" name="type" id="producttype"
                       value="<?php echo $this->getRequest()->getParam('type') ?>"/>
                <input type="hidden" name="wstoreids" id="wstoreids" value="<?php echo $this->getStoreId(); ?>"
                       title="wstoreids" class=""/>
                <ul class="form-list" id="cmsmart_bodymain">
                    <li style="display:none">
                        <label class="label required"><?php echo __('Attribute Set') ?>:</label>

                        <div class="input-box">
                            <select name="set" class="required-entry">
                                <?php foreach ($this->getAllowedSets() as $set) { ?>
                                    <option value="<?php echo $set['value'] ?>" <?php echo ($set['value'] == $this->getRequest()->getParam('set')) ? ('selected') : (''); ?>><?php echo $set['label'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </li>
                    <li>
                        <label class="label"><?php echo __('Product Category') ?>:</label>
                        <div class="cmsmart_field cmsmart_category">
                            <div class="cmsmart_for_validation">
                                <div id="cmsmart_category_label"><?php echo __("CATEGORIES"); ?></div>
                                <div id="nb_button_cate">
                                    <div class="sidetreecontrol"><a href="?#"><?php echo __('Collapse All') ?></a> | <a
                                            href="?#"><?php echo __('Expand All') ?></a></div>
                                    <div id="top_tree">
                                        <?php echo $helper->top_createTree($arrayCategories, 2,0,-1 , $product); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <label class="label required"><?php echo __('Product Name') ?>:</label>
                        <div class="input-box">
                            <input type="text" class="required-entry input-text" name="product[name]" id="name"
                                   value="<?php echo isset($product) ? $product->getName() : ''; ?>"/>
                        </div>
                    </li>
                    <li>
                        <label class="label required"><?php echo __('Description') ?>:</label>
                        <div class="input-box">
                            <textarea name="product[description]" class="input-text" id="description" rows="5"
                                      cols="75"><?php echo isset($product) ? $product->getDescription() : ''; ?></textarea>
                        </div>
                        <script>
                            require([
                                'jquery',
                                'mage/adminhtml/wysiwyg/tiny_mce/setup'
                            ], function (jQuery) {

                                var config = '',
                                    editor;

                                jQuery.extend(config, {
                                    settings: {
                                        theme_advanced_buttons1: 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                        'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                                        theme_advanced_buttons2: null,
                                        theme_advanced_buttons3: null,
                                        theme_advanced_buttons4: null,
                                        theme_advanced_statusbar_location: null
                                    },
                                    files_browser_window_url: false
                                });

                                editor = new tinyMceWysiwygSetup(
                                    'description',
                                    config
                                );

                                editor.turnOn();

                                jQuery('#description')
                                    .addClass('wysiwyg-editor')
                                    .data(
                                        'wysiwygEditor',
                                        editor
                                    );
                            });
                        </script>
                    </li>
                    <li>
                        <label class="label"><?php echo __('Short Description') ?>:</label>
                        <div class="input-box">
                        <textarea name="product[short_description]" id="short_description" rows="5" cols="75"
                                  class="input-text"><?php echo isset($product) ? $product->getShortDescription() : ''; ?></textarea>
                        </div>

                        <script>
                            require([
                                'jquery',
                                'mage/adminhtml/wysiwyg/tiny_mce/setup'
                            ], function (jQuery) {

                                var config = '',
                                    editor;

                                jQuery.extend(config, {
                                    settings: {
                                        theme_advanced_buttons1: 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                        'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                                        theme_advanced_buttons2: null,
                                        theme_advanced_buttons3: null,
                                        theme_advanced_buttons4: null,
                                        theme_advanced_statusbar_location: null
                                    },
                                    files_browser_window_url: false
                                });

                                editor = new tinyMceWysiwygSetup(
                                    'short_description',
                                    config
                                );

                                editor.turnOn();

                                jQuery('#short_description')
                                    .addClass('wysiwyg-editor')
                                    .data(
                                        'wysiwygEditor',
                                        editor
                                    );
                            });
                        </script>
                    </li>
                    <li>
                        <label class="label required"><?php echo __('SKU') ?>:</label>
                        <?php if ($skuType == 'dynamic' && $skuPrefix) : ?>
                            <?php echo "(Prefix - " . $skuPrefix . ")";?>
                            <span><?php echo isset($product) ? $product->getSku() : ''; ?></span>
                        <?php else: ?>
                            <div class="control">
                                <input name="product[sku]" id="sku" class="required-entry input-text" type="text"
                                       value="<?php echo isset($product) ? $product->getSku() : ''; ?>"/>
                            </div>
                            <div id="skuavail">
                                <span class="success-msg skuavailable"><?php echo __('SKU Available') ?></span>
                            </div>
                            <div id="skunotavail">
                                <span class="error-msg skunotavailable"><?php echo __('SKU Already Exist') ?></span>
                            </div>
                        <?php endif; ?>
                    </li>
                    <li>
                        <label class="label required"><?php echo __('Price') ?>
                            <b><?php echo " (" . $this->getCurrencySymbol() . ")"; ?></b>:</label>
                        <div class="input-box">
                            <input type="text" class="required-entry validate-zero-or-greater input-text"
                                   name="product[price]"
                                   id="price"
                                   value="<?php echo isset($product) ? $product->getPrice() : ''; ?>"/>
                        </div>
                    </li>
                    <li>
                        <label class="label"><?php echo __('Special Price') ?>
                            <b><?php echo " (" . $this->getCurrencySymbol() . ")"; ?></b>:</label>
                        <div class="input-box">
                            <input type="text" class="widthinput input-text validate-zero-or-greater"
                                   name="product[special_price]"
                                   id="special_price"
                                   value="<?php echo isset($product) ? $product->getSpecialPrice() : ''; ?>"/>
                        </div>
                    </li>
                    <li>
                        <label class="label"><?php echo __('Special Price From') ?>:</label>
                        <div class="input-box">
                            <input type="text" name="product[special_from_date]" id="special_from_date"
                                   class="datepicker input-text"
                                   value="<?php echo isset($product) ? $this->formatDate($product->getSpecialFromDate()) : ''; ?>"/>
                        </div>
                    </li>
                    <li>
                        <label class="label"><?php echo __('Special Price To') ?>:</label>
                        <div class="input-box">
                            <input type="text" name="product[special_to_date]" id="special_to_date"
                                   class="datepicker input-text"
                                   value="<?php echo isset($product) ? $this->formatDate($product->getSpecialToDate()) : ''; ?>"/>
                        </div>
                    </li>
                    <input id="inventory_manage_stock" type="hidden" name="product[stock_data][manage_stock]" value="1">
                    <input type="hidden" value="1" name="product[stock_data][use_config_manage_stock]"
                           id="inventory_use_config_manage_stock">
                    <li>
                        <label class="label required"><?php echo __('Stock') ?>:</label>
                        <div class="control">
                            <input type="text" class="required-entry validate-number input-text"
                                   name="product[quantity_and_stock_status][qty]" id="qty"
                                   value="<?php echo isset($product) ? $product->getData('quantity_and_stock_status')['qty'] : ''; ?>"/>
                        </div>
                    </li>
                    <li>
                        <label class="label required"><?php echo __('Stock Availability') ?>:</label>
                        <div class="control">
                            <select class="select" name="product[quantity_and_stock_status][is_in_stock]">
                                <?php if (isset($product)): ?>
                                    <option
                                        value="1" <?php echo ($product->getData('quantity_and_stock_status')['is_in_stock'] == 1) ? ('selected') : ('') ?>><?php echo __("In Stock"); ?></option>
                                    <option
                                        value="0" <?php echo !($product->getData('quantity_and_stock_status')['is_in_stock']) ? ('selected') : ('') ?>><?php echo __("Out Stock"); ?></option>
                                <?php else: ?>
                                    <option value="1"><?php echo __("In Stock"); ?></option>
                                    <option value="0"><?php echo __("Out of Stock"); ?></option>
                                <?php endif; ?>
                            </select>
                        </div>
                    </li>
                    <li>
                        <label class="label required"><?php echo __('Visibility') ?>:</label>

                        <div class="input-box">
                            <select id="visibility" class=" required-entry required-entry select"
                                    name="product[visibility]">
                                <option value=""><?php echo __('Please Select') ?></option>
                                <?php
                                $product_visibility = $this->getProductVisibility();
                                foreach ($product_visibility as $key => $value) {
                                    ?>
                                    <?php if (isset($product)): ?>
                                        <option value="<?php echo $key ?>" <?php echo ($product->getVisibility() == $key) ? ('selected') : ('');?>><?php echo $value ?></option>
                                    <?php else : ?>
                                        <option value="<?php echo $key ?>"><?php echo $value ?></option>
                                    <?php endif; ?>
                                    <?php
                                } ?>
                            </select>
                        </div>
                    </li>
                    <li>
                        <label class="label required"><?php echo __('Tax Class') ?>:</label>
                        <div class="input-box">
                            <select id="tax_class_id" class=" required-entry required-entry select"
                                    name="product[tax_class_id]">
                                <option value="0"><?php echo __('None') ?></option>
                                <?php
                                $taxes = $this->getTaxClassCollection()->addFieldToFilter('class_type', array('eq' => 'PRODUCT'));
                                foreach ($taxes as $tax) {
                                    ?>
                                    <?php if (isset($product)): ?>
                                        <option value="<?php echo $tax->getId() ?>" <?php echo ($product->getTaxClassId() == $tax->getId()) ? ('selected') : ('');?>><?php echo $tax->getClassName() ?></option>
                                    <?php else : ?>
                                        <option value="<?php echo $tax->getId() ?>"><?php echo $tax->getClassName() ?></option>
                                    <?php endif; ?>
                                    <?php
                                } ?>
                            </select>
                        </div>
                    </li>
                    <li>
                        <label class="label <?php echo $productType == 'simple' || $productType == 'configuration' ? 'required' : ''?>"><?php echo __('Weight') ?>:</label>
                        <div class="input-box product-weight">
                            <input type="text"
                                   class="validate-number validate-zero-or-greater validate-number-range number-range-0-99999999.9999 input-text <?php echo $productType == 'simple' || $productType == 'configuration' ? 'required-entry' : ''?>"
                                   name="product[weight]" id="weight" value="<?php echo isset($product) ? $product->getWeight() : ''; ?>"/>
                        </div>
                        <div class="input-box select-check-weight">
                            <select id="check-weight" class="select" name="product[product_has_weight]">
                                <?php if (isset($product)): ?>
                                    <option value="1" <?php echo ($product->getWeight()) ? ('selected') : ('') ?>><?php echo __("This item has weight"); ?></option>
                                    <option value="0" <?php echo !($product->getWeight()) ? ('selected') : ('') ?>><?php echo __("This item has no weight"); ?></option>
                                <?php else: ?>
                                    <option value="1"><?php echo __('This item has weight') ?></option>
                                    <option value="0" <?php echo $productType == 'downloadable' || $productType == 'virtual' ? 'selected' : ''?>><?php echo __('This item has no weight') ?></option>
                                <?php endif; ?>
                            </select>
                        </div>
                    </li>
                    <li>
                        <label class="label"><?php echo __('Meta Title') ?>:</label>

                        <div class="input-box">
                            <input type="text" class="input-text" name="product[meta_title]" id="meta_title" value="<?php echo isset($product) ? $product->getMetaTitle() : ''; ?>"/>
                        </div>
                    </li>
                    <li>
                        <label class="label"><?php echo __('Meta Keywords') ?>:</label>

                        <div class="input-box">
                            <textarea name="product[meta_keyword]" id="meta_keyword" rows="5" cols="75"><?php echo isset($product) ? $product->getMetaKeyword() : ''; ?></textarea>
                        </div>
                    </li>
                    <li>
                        <label class="label"><?php echo __('Meta Description') ?>:</label>

                        <div class="input-box">
                            <textarea name="product[meta_description]" id="meta_description" rows="5" cols="75"><?php echo isset($product) ? $product->getMetaDescription() : ''; ?></textarea>
                        </div>
                    </li>

                    <?php echo $this->getChildHtml(); ?>
                </ul>
            </div>
        </div>
    </div>
</form>

<div class="buttons-set">
    <p class="label required"><?php echo __('Required Fields') ?></p>

    <p class="back-link">
        <a href="javascript:;" onclick="javascript: window.history.back();"
           class="left">&laquo; <?php echo __('Back') ?></a>
    </p>
</div>

<script>
    require([
        "jquery",
        "mage/mage"
    ], function ($) {
        var dataForm = $('#form-customer-product-new');
        dataForm.mage('validation', {});
    });
</script>

<script>
    requirejs(['jquery', 'cmsmartTreeview'], function ($) {

        $(function () {
            $("#top_tree").treeview({
                collapsed: true,
                animated: "medium",
                control: ".sidetreecontrol",
                persist: "location"
            });
            $(".sidetreecontrol a:eq(0)").trigger("click");
        });

        function expand_prags(str) {

        }
    });
</script>

<?php
$formData = [
    'checkSkuAjaxUrl' => $block->getUrl('marketplace/product/checksku', ['_secure' => $this->getRequest()->isSecure()])
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "*": {
            "productEditForm": <?php /* @noEscape */
    echo $serializedFormData; ?>
        }
    }
</script>

<script type='text/javascript'>
    require(['jquery', 'prototype', 'domReady!'], function($) {
        var qty = $('#qty'),
            productType = $('#product_type_id').val(),
            stockAvailabilityField = $('#quantity_and_stock_status'),
            manageStockField = $('#inventory_manage_stock'),
            useConfigManageStockField = $('#inventory_use_config_manage_stock'),
            fieldsAssociations = {
                'qty': 'inventory_qty',
                'quantity_and_stock_status': 'inventory_stock_availability'
            };

        var qtyDefaultValue = qty.val();
    })
</script>
<script>
    require([
        "jquery",
        "Cmsmart_Marketplace/catalog/type-events"
    ], function($, TypeSwitcher){
        var $form = $('[data-form=edit-product]');
        $form.data('typeSwitcher', TypeSwitcher.init());
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Cmsmart_Marketplace/js/product/weight-handler": {},
            "Cmsmart_Marketplace/catalog/apply-to-type-switcher": {}
        }
    }
</script>






