<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block Cmsmart\Marketplace\Block\Catalog\Product\View */

$vacation = $block->getVacation();
$_product = $block->getProduct();
$buttonTitle = __('Add to Cart');

if($vacation['add_to_cart_label']) {
    $buttonTitle = $vacation['add_to_cart_label'];
}
?>

<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <?php if($vacation):?>
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button" disabled>
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                <?php else:?>
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                <?php endif;?>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>