<?php
/** @var $block \Cmsmart\Marketplace\Block\Catalog\Product\Edit\Tab\Associated */

$crosssellProducts = [];
if ($block->getProduct()->getId()) {
    $productColl = $block->getProduct();
    $crosssellProductColl = $productColl->getProductLinks();
    foreach ($crosssellProductColl as $key => $value) {
        if ($value['link_type'] == 'crosssell') {
            $productBySku = $block->getProductBySku($value['linked_product_sku']);
            array_push($crosssellProducts, $productBySku->getId());
        }
    }
}
?>
<li>
<div id="crosssell-product-block" style="width: 98%;overflow: auto;">
    <h3 class="title">
        <?php /* @noEscape */ echo __('Cross-Sell Products'); ?>
    </h3>
    <?php /* @noEscape */ echo __('These "impulse-buy" products appear next to the shopping cart as cross-sells to the items already in the shopping cart.'); ?>
    <div id="crosssell-product-block-loader" class="admin__data-grid-outer-wrap" style="display:block;">
        <div class="admin__data-grid-loading-mask">
            <div class="spinner">
                <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
            </div>
        </div>
    </div>
    <input type="button" id="hideshow-crosssell-product" value="show">
    <div id="crosssell-product-block-wrapper" style="display:none;">
        <?php echo $block->getChildHtml(); ?>        
    </div>
    <script id="crosssell-product-template" type="text/x-magento-template">
	    <div id="crosssell-product-record<%- data.id %>">
	        <input name="links[crosssell][<%- data.index %>][id]" type="hidden" value="<%- data.id %>">
			<input name="links[crosssell][<%- data.index %>][name]" type="hidden" value="<%- data.name %>">
			<input name="links[crosssell][<%- data.index %>][status]" type="hidden" value="<%- data.status %>">
			<input name="links[crosssell][<%- data.index %>][attribute_set]" type="hidden" value="<%- data.attribute_set %>">
			<input name="links[crosssell][<%- data.index %>][sku]" type="hidden" value="<%- data.sku %>">
			<input name="links[crosssell][<%- data.index %>][price]" type="hidden" value="<%- data.price %>">
			<input name="links[crosssell][<%- data.index %>][thumbnail]" type="hidden" value="<%- data.thumbnail %>">
			<input name="links[crosssell][<%- data.index %>][position]" type="hidden" value="<%- data.position %>">
			<input name="links[crosssell][<%- data.index %>][record_id]" type="hidden" value="<%- data.record_id %>">
		</div>
    </script>
</div>
</li>
<?php
$formData = [
    'crosssellProductId' => '#cmsmart-mp-body',
    'templateId' => '#crosssell-product-template',
    'gridCheckbox' => '.admin__control-checkbox',
    'crosssellProducts' => $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($crosssellProducts)
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>

<script>
    requirejs(['jquery'], function ($) {
        $(document).ready(function(){
            $('#hideshow-crosssell-product').on('click', function(event) {
                $('#crosssell-product-block-wrapper').toggle('show');

                if ($(this).val() ==='show') {
                    $(this).val('hide');
                } else {
                    $(this).val('show');
                }
            });
        });
    });
</script>

<script type="text/x-magento-init">
    {
        "#crosssell-product-block": {
            "crosssellProduct": <?php /* @noEscape */ echo $serializedFormData; ?>
        }
    }
</script>
