<?php
/** @var $block \Cmsmart\Marketplace\Block\Catalog\Product\Edit\Tab\Associated */

$relatedProducts = [];
if ($block->getProduct()->getId()) {
    $productColl = $block->getProduct();
    $relatedProductColl = $productColl->getProductLinks();
    foreach ($relatedProductColl as $key => $value) {
        if ($value['link_type'] == 'related') {
            $productBySku = $block->getProductBySku($value['linked_product_sku']);
            array_push($relatedProducts, $productBySku->getId());
        }
    }
}
?>
<li>
<div id="related-product-block" style="width: 98%;overflow: auto;">
    <h3 class="title">
        <?php /* @noEscape */ echo __('Related Products'); ?>
    </h3>
    <?php /* @noEscape */ echo __('Related products are shown to customers in addition to the item the customer is looking at.'); ?>
    <div id="related-product-block-loader" class="admin__data-grid-outer-wrap" style="display:block;">
        <div class="admin__data-grid-loading-mask">
            <div class="spinner">
                <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
            </div>
        </div>
    </div>
    <input type="button" id="hideshow-related-product" value="show">
    <div id="related-product-block-wrapper" style="display:none;">
        <?php echo $block->getChildHtml(); ?>
    </div>
    <script id="related-product-template" type="text/x-magento-template">
	    <div id="related-product-record<%- data.id %>">
	        <input name="links[related][<%- data.index %>][id]" type="hidden" value="<%- data.id %>">
			<input name="links[related][<%- data.index %>][name]" type="hidden" value="<%- data.name %>">
			<input name="links[related][<%- data.index %>][status]" type="hidden" value="<%- data.status %>">
			<input name="links[related][<%- data.index %>][attribute_set]" type="hidden" value="<%- data.attribute_set %>">
			<input name="links[related][<%- data.index %>][sku]" type="hidden" value="<%- data.sku %>">
			<input name="links[related][<%- data.index %>][price]" type="hidden" value="<%- data.price %>">
			<input name="links[related][<%- data.index %>][thumbnail]" type="hidden" value="<%- data.thumbnail %>">
			<input name="links[related][<%- data.index %>][position]" type="hidden" value="<%- data.position %>">
			<input name="links[related][<%- data.index %>][record_id]" type="hidden" value="<%- data.record_id %>">
		</div>
    </script>
</div>
</li>
<?php
$formData = [
    'relatedProductId' => '#cmsmart-mp-body',
    'templateId' => '#related-product-template',
    'gridCheckbox' => '.admin__control-checkbox',
    'relatedProducts' => $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($relatedProducts)
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>

<script>
    requirejs(['jquery'], function ($) {
        $(document).ready(function(){
            $('#hideshow-related-product').on('click', function(event) {
                $('#related-product-block-wrapper').toggle('show');

                if ($(this).val() ==='show') {
                    $(this).val('hide');
                } else {
                    $(this).val('show');
                }
            });
        });
    });
</script>

<script type="text/x-magento-init">
    {
        "#related-product-block": {
            "relatedProduct": <?php /* @noEscape */ echo $serializedFormData; ?>
        }
    }
</script>

