<?php
$_shopbybrand = $this->getCollection(); 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$appState = $objectManager->get('\Magento\Framework\App\State');
$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categories = $categoryCollection->create();
$categories->addAttributeToSelect('*');
$category1 = explode(",",$this->getCategorybrand());
$branddisplay = [];
$count11 = 0;
$j=1;
$h=1; 
$currentStore = $storeManager->getStore(); 
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$logopath = $this->getViewFileUrl('Netbaseteam_Shopbybrand::images/logo.png');
$brandpath = $this->getViewFileUrl('Netbaseteam_Shopbybrand::images/search.png');
$checkhome = $block->getHomeName();  
		var_dump($checkhome);die;
?>

<div class="home-product-slider nb-list products-grid">
	<?php
		$cateinstance = $objectManager->create('Magento\Catalog\Model\CategoryFactory');
		$cateid = $category->getId();
		$allcategoryproduct = $cateinstance->create()->load($cateid)->getProductCollection()->addAttributeToSelect('*');
		foreach ($allcategoryproduct as $product) {
			foreach ($_shopbybrand as $shopbybrandItem){
				$path = $mediaUrl.'//Shopbybrand'.'//'.$shopbybrandItem->getLogo(); 
				$productbrand= explode("&", $shopbybrandItem->getproduct_ids());
				$brandid = $shopbybrandItem->getBrandId();
				foreach ($productbrand as $item){
					if ($item == $product->getId() ) { ?> 
						<?php if (in_array($brandid,$branddisplay)): ?>
							
						<?php else: ?>
							<?php if ($count11<10): ?>
								<div class="item">
									<a href=""><img src=" <?php echo $path ?>"/></a>
								</div>
								<?php 
									array_push($branddisplay,$brandid);
									$count11++;
								?>
							<?php endif ?>
						<?php endif ?>
						<?php  
					}
				}
			}
		}
	?>
</div>
							