<?php 
$helper = $this->helper('Cmsmart\Marketplace\Helper\Data');
$layout = $helper->getLandingPage();
?>
<?php if($layout == '1'):?>
<div class="landing-page">
    <div>
    	<!-- sell-with-us01 -->
        <section class="sell-with-us01">
        	<div class="container">
        		<div class="row">
	        		<div class="col-md-6">
	        			<div class="sell-left">
	        				<h2>Sell with us</h2>
	   						<p>We are largest growing community to sell online, Come and Join us.</p>
	        			</div>
	        		</div>
	        		<div class="col-md-6">
	        			<div class="sell-right">
	        				<h2>Register As Seller</h2>
	        				<!-- <form class="register">
	        				
	        					<div class="form-name">
		        					<div class="row">
		        						<div class="col-md-6">
		        							<div class="form-group"> 
											    <input type="text" name="firstname" class="form-control"  placeholder="First Name *">
											</div>
		        						</div>
		        						<div class="col-md-6">
		        							<div class="form-group"> 
											    <input type="text" name="lastname" class="form-control"  placeholder="Last Name *">
											</div>
		        						</div>
		        					</div>
	        					</div>
	        					<div class="form-email">
	    							<div class="form-group">
									    <input type="email" name="email" class="form-control"  placeholder="Email *">
									</div>
								</div>
	        					<div class="form-url">
	    							<div class="form-group">
									    <input type="text" name="shop_id" class="form-control" placeholder="Shop URL*">
									</div>
								</div>
								<div class="form-pass">
		        					<div class="row">
		        						<div class="col-md-6">
		        							<div class="form-group"> 
											    <input type="password" name="password" data-password-min-length="8" data-password-min-character-sets="3" data-validate="{required:true, 'validate-customer-password':true}" class="form-control" aria-required="true" placeholder="Password*">
											</div>
		        						</div>
		        						<div class="col-md-6">
		        							<div class="form-group"> 
											    <input type="password" name="password_confirmation" class="form-control"  data-validate="{required:true, equalTo:'#password'}" aria-required="true" placeholder="Confirm Password*">
											</div>
		        						</div>
		        					</div>
		        				</div>
		        				<div class="form-creatAccout">
		        					<div class="row">
		        						<div class="col-md-6">
		        							<div class="creatAccount-left">
		        								<div class="checkbox">
												    <label>
												      <input type="checkbox"> 
												      <span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
												      Yes, I agree to Terms and Conditions	
												    </label>
								  				</div>
		        							</div>
		        						</div>
		        						<div class="col-md-6">
		        							<div class="creatAccount-right">
		        								<a href="" class="button btn-creatAccount"><span>Create an Account</span></a>
		        							</div>
		        						</div>
		        					</div>
		        					
		        				</div>
	        				</form> -->
							<?php
							/**
							 * Create account form template
							 *
							 * @var $block \Magento\Customer\Block\Form\Register
							 */
							?>
							<?php echo $block->getChildHtml('form_fields_before') ?>
							<?php /* Extensions placeholder */ ?>
							<?php echo $block->getChildHtml('customer.form.register.extra') ?>
							<form class="form create account form-create-account" action="<?php /* @escapeNotVerified */
							echo $block->getUrl('marketplace/account/createpost') ?>" method="post" id="form-validate"
								enctype="multipart/form-data"
								autocomplete="off">
								<fieldset class="fieldset create info">
									<legend class="legend"><span><?php /* @escapeNotVerified */
											echo __('Personal Information') ?></span></legend>
									<br>
									<input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */
									echo $block->getSuccessUrl() ?>">
									<input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */
									echo $block->getErrorUrl() ?>">
									<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

									<?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
									<?php if ($_dob->isEnabled()): ?>
										<?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
									<?php endif ?>

									<?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
									<?php if ($_taxvat->isEnabled()): ?>
										<?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
									<?php endif ?>

									<?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
									<?php if ($_gender->isEnabled()): ?>
										<?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
									<?php endif ?>
								</fieldset>
								<?php if ($block->getShowAddressFields()): ?>
									<fieldset class="fieldset address">
										<legend class="legend"><span><?php /* @escapeNotVerified */
												echo __('Address Information') ?></span></legend>
										<br>
										<input type="hidden" name="create_address" value="1"/>

										<div class="field company">
											<label for="company" class="label"><span><?php /* @escapeNotVerified */
													echo __('Company') ?></span></label>

											<div class="control">
												<input type="text" name="company" id="company"
													value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>"
													title="<?php /* @escapeNotVerified */
													echo __('Company') ?>" class="input-text <?php /* @escapeNotVerified */
												echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
											</div>
										</div>
										<div class="field telephone">
											<label for="telephone" class="label"><span><?php /* @escapeNotVerified */
													echo __('Phone Number') ?></span></label>

											<div class="control">
												<input type="text" name="telephone" id="telephone"
													value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>"
													title="<?php /* @escapeNotVerified */
													echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */
												echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
											</div>
										</div>

										<?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

										<div class="field street required">
											<label for="street_1" class="label"><span><?php /* @escapeNotVerified */
													echo __('Street Address') ?></span></label>

											<div class="control">
												<input type="text" name="street[]"
													value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>"
													title="<?php /* @escapeNotVerified */
													echo __('Street Address') ?>" id="street_1"
													class="input-text <?php /* @escapeNotVerified */
													echo $_streetValidationClass ?>">

												<div class="nested">
													<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
													<?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
														<div class="field additional">
															<label class="label" for="street_<?php /* @escapeNotVerified */
															echo $_i ?>">
																<span><?php /* @escapeNotVerified */
																	echo __('Address') ?></span>
															</label>

															<div class="control">
																<input type="text" name="street[]"
																	value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>"
																	title="<?php /* @escapeNotVerified */
																	echo __('Street Address %1', $_i) ?>"
																	id="street_<?php /* @escapeNotVerified */
																	echo $_i ?>" class="input-text <?php /* @escapeNotVerified */
																echo $_streetValidationClass ?>">
															</div>
														</div>
													<?php endfor; ?>
												</div>
											</div>
										</div>

										<div class="field required">
											<label for="city" class="label"><span><?php /* @escapeNotVerified */
													echo __('City') ?></span></label>

											<div class="control">
												<input type="text" name="city"
													value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>"
													title="<?php /* @escapeNotVerified */
													echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */
												echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>"
													id="city">
											</div>
										</div>

										<div class="field region required">
											<label for="region_id" class="label"><span><?php /* @escapeNotVerified */
													echo __('State/Province') ?></span></label>

											<div class="control">
												<select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */
												echo __('State/Province') ?>" class="validate-select" style="display:none;">
													<option value=""><?php /* @escapeNotVerified */
														echo __('Please select a region, state or province.') ?></option>
												</select>
												<input type="text" id="region" name="region"
													value="<?php echo $block->escapeHtml($block->getRegion()) ?>"
													title="<?php /* @escapeNotVerified */
													echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */
												echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"
													style="display:none;">
											</div>
										</div>

										<div class="field zip required">
											<label for="zip" class="label"><span><?php /* @escapeNotVerified */
													echo __('Zip/Postal Code') ?></span></label>

											<div class="control">
												<input type="text" name="postcode"
													value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>"
													title="<?php /* @escapeNotVerified */
													echo __('Zip/Postal Code') ?>" id="zip"
													class="input-text validate-zip-international <?php /* @escapeNotVerified */
													echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
											</div>
										</div>

										<div class="field country required">
											<label for="country" class="label"><span><?php /* @escapeNotVerified */
													echo __('Country') ?></span></label>

											<div class="control">
												<?php echo $block->getCountryHtmlSelect() ?>
											</div>
										</div>
										<?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes'); ?>
										<?php if ($addressAttributes): ?>
											<?php $addressAttributes->setEntityType('customer_address'); ?>
											<?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
											<?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address'); ?>
											<?php echo $addressAttributes->setShowContainer(false)->toHtml() ?>
										<?php endif; ?>
										<input type="hidden" name="default_billing" value="1">
										<input type="hidden" name="default_shipping" value="1">
									</fieldset>

								<?php endif; ?>
								<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
								echo __('* Required Fields') ?>">

									<div class="field required">
										<label for="email_address" class="label"><span><?php /* @escapeNotVerified */
												echo __('Email') ?></span></label>

										<div class="control">
											<input type="email" name="email" autocomplete="email" id="email_address"
												value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>"
												title="<?php /* @escapeNotVerified */
												echo __('Email') ?>" class="input-text"
												data-validate="{required:true, 'validate-email':true}">
										</div>
									</div>
									<div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
										<label for="password" class="label"><span><?php /* @escapeNotVerified */
												echo __('Password') ?></span></label>

										<div class="control">
											<input type="password" name="password" id="password"
												title="<?php /* @escapeNotVerified */
												echo __('Password') ?>"
												class="input-text"
												data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
												data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
												data-validate="{required:true, 'validate-customer-password':true}"
												autocomplete="off">

											<div id="password-strength-meter-container" data-role="password-strength-meter">
												<div id="password-strength-meter" class="password-strength-meter">
													<?php /* @escapeNotVerified */
													echo __('Password Strength'); ?>:
												<span id="password-strength-meter-label" data-role="password-strength-meter-label">
													<?php /* @escapeNotVerified */
													echo __('No Password'); ?>
												</span>
												</div>
											</div>
										</div>

									</div>
									<div class="field confirmation required">
										<label for="password-confirmation" class="label"><span><?php /* @escapeNotVerified */
												echo __('Confirm Password') ?></span></label>

										<div class="control">
											<input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */
											echo __('Confirm Password') ?>" id="password-confirmation" class="input-text"
												data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
										</div>
									</div>
									<?php echo $block->getChildHtml('form_additional_info'); ?>
									<?php if ($block->isNewsletterEnabled()): ?>
										<div class="field choice newsletter">
											<input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */
											echo __('Sign Up for Newsletter') ?>" value="1"
												id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
												class="checkbox">
											<label for="is_subscribed" class="label"><span><?php /* @escapeNotVerified */
													echo __('Sign Up for Newsletter') ?></span></label>
										</div>
										<?php /* Extensions placeholder */ ?>
										<?php echo $block->getChildHtml('customer.form.register.newsletter') ?>
									<?php endif ?>
								</fieldset>
								
								<div class="actions-toolbar">
									<div class="primary">
										<button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */
										echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */
												echo __('Create an Account') ?></span></button>
									</div>
									<div class="secondary">
										<a class="action back"
										href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */
												echo __('Back') ?></span></a>
									</div>
								</div>
							</form>
							<script>
								require([
									'jquery',
									'mage/mage'
								], function ($) {

									var dataForm = $('#form-validate');
									var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

									dataForm.mage('validation', {
										<?php if ($_dob->isEnabled()): ?>
										errorPlacement: function (error, element) {
											if (element.prop('id').search('full') !== -1) {
												var dobElement = $(element).parents('.customer-dob'),
													errorClass = error.prop('class');
												error.insertAfter(element.parent());
												dobElement.find('.validate-custom').addClass(errorClass)
													.after('<div class="' + errorClass + '"></div>');
											}
											else {
												error.insertAfter(element);
											}
										},
										ignore: ':hidden:not(' + ignore + ')'
										<?php else: ?>
										ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
										<?php endif ?>
									}).find('input:text').attr('autocomplete', 'off');

								});
							</script>
							<?php if ($block->getShowAddressFields()): ?>
								<script type="text/x-magento-init">
							{
								"#country": {
									"regionUpdater": {
										"optionalRegionAllowed": <?php /* @escapeNotVerified */
									echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
										"regionListId": "#region_id",
										"regionInputId": "#region",
										"postcodeId": "#zip",
										"form": "#form-validate",
										"regionJson": <?php /* @escapeNotVerified */
									echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
										"defaultRegion": "<?php /* @escapeNotVerified */
									echo $block->getFormData()->getRegionId() ?>",
										"countriesWithOptionalZip": <?php /* @escapeNotVerified */
									echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
									}
								}
							}


								</script>
							<?php endif; ?>
	        			</div>	
	        		</div>
	        	</div>
        	</div>
        </section>
        <!-- set up  -->
		<section class="marketplace setup">
			<div class="container">
				<div class="section-heading">
					<h2>Really easy to setup and customize</h2>
					<div class="rule"></div>
				</div>
				<div class="section-content setup-customize">
					<div class="setup-customize__item">
						<div class="display-flex">
							<a href="#"><img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/setup1.png'); ?>" alt="setup01"></a>
						</div>
						<h3>Create an Account</h3>
					</div>
					<div class="setup-customize__item">
						<div class="display-flex">
							<a href="#"><img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/setup2.png'); ?>" alt="setup02"></a>
						</div>	
						<h3>Customize your Profile</h3>
					</div>
					<div class="setup-customize__item">
						<div class="display-flex">
							<a href="#"><img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/setup3.png'); ?>" alt="setup03"></a>	
						</div>
						<h3>Add your Details</h3>
					</div>
					<div class="setup-customize__item">
						<div class="display-flex">
							<a href="#"><img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/setup4.png'); ?>" alt="setup04"></a>
						</div>
						<h3>Add your Product Listing</h3>
					</div>
					<div class="setup-customize__item">
						<div class="display-flex">
							<a href="#"><img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/setup5.png'); ?>" alt="setup05"></a>
						</div>
						<h3>Sell your Product and Earn Profits</h3>
					</div>
				</div>
			</div>
		</section>
		<!-- why to sell -->
		<section class="marketplace why-to-sell">
			<div class="container">
				<div class="section-heading">
					<h2>Why to sell with us</h2>
					<div class="rule"></div>
				</div>
			
				<div class="section-content">
					<div class="row display-clear">
						<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
							<div class="whyToSell-item">
								<div class="whyToSell-img">
									<a href="#">
										<span class="whyToSell-icon display-flex">
											<img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/why1.png'); ?>" alt="why1">
										</span>
									</a>
								</div>
								<div class="whyToSell-text">
									<h3><a href="#">Huge Buyers</a></h3>
									<p>Get your product showcased to a huge range of customers, as everyday many user shops from us.</p>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
							<div class="whyToSell-item">
								<div class="whyToSell-img">
									<a href="#">
										<span class="whyToSell-icon display-flex">
											<img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/why2.png'); ?>" alt="why2">
										</span>
									</a>
								</div>
								<div class="whyToSell-text">
									<h3><a href="#">Ask Questions</a></h3>
									<p>If you ever get stuck, let us know and we will help you with the best we have in minimum possible time.</p>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
							<div class="whyToSell-item">
								<div class="whyToSell-img">
									<a href="#">
										<span class="whyToSell-icon display-flex">
											<img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/why3.png'); ?>" alt="why3">
										</span>
									</a>
								</div>
								<div class="whyToSell-text">
									<h3><a href="#">Quick Payments</a></h3>
									<p>Once goods have been successfully delivered to respective customers, you can request for payout</p>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
							<div class="whyToSell-item">
								<div class="whyToSell-img">
									<a href="#">
										<span class="whyToSell-icon display-flex">
											<img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/why4.png'); ?>" alt="why4">
										</span>
									</a>
								</div>
								<div class="whyToSell-text">
									<h3><a href="#">Manage Your Orders</a></h3>
									<p>Manage your orders at maximum ease and help customers to have a better shopping experience.</p>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
							<div class="whyToSell-item">
								<div class="whyToSell-img">
									<a href="#">
										<span class="whyToSell-icon display-flex">
											<img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/why5.png'); ?>" alt="why5">
										</span>
									</a>
								</div>
								<div class="whyToSell-text">
									<h3><a href="#">Earn Badges</a></h3>
									<p>Once you climb a milestone you get awarded with a badge, which make you look like more pro.</p>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
							<div class="whyToSell-item">
								<div class="whyToSell-img">
									<a href="#">
										<span class="whyToSell-icon display-flex">
											<img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/why6.png'); ?>" alt="why6">
										</span>
									</a>
								</div>
								<div class="whyToSell-text">
									<h3><a href="#">Get Yourself Verified</a></h3>
									<p>Add a verified brooch to your profile by providing very neccessary some business details and documents..</p>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
							<div class="whyToSell-item">
								<div class="whyToSell-img">
									<a href="#">
										<span class="whyToSell-icon display-flex">
											<img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/why7.png'); ?>" alt="why7">
										</span>
									</a>
								</div>
								<div class="whyToSell-text">
									<h3><a href="#">Customize Profile</a></h3>
									<p>Customize your profile with information like profile logo, shop location, shipping and refund policies.</p>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
							<div class="whyToSell-item">
								<div class="whyToSell-img">
									<a href="#">
										<span class="whyToSell-icon display-flex">
											<img src="<?php echo $this->getViewFileUrl('Cmsmart_Marketplace::images/marketplace01/why8.png'); ?>" alt="why8">
										</span>
									</a>
								</div>
								<div class="whyToSell-text">
									<h3><a href="#">Add Media</a></h3>
									<p>Embed video YouTube to make your account more genuine and stand out in the queue.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- open-shop -->
		<section class="open-shop text-center">
			<div class="container">
				<h2>Open your online shop & Explore a new world of market with more then millions of shoppers</h2>
				<a href="<?php /* @escapeNotVerified */
							echo $block->getUrl('customer/account/login/') ?>" class="button btn-open-shop">open your shop</a>
			</div>
		</section>
    </div>
    <button onclick="topFunction()" id="myBtn" title="Go to top"><i class="fa fa-arrow-up" aria-hidden="true"></i></button>
</div>
<?php endif;?>