<?php

// @codingStandardsIgnoreFile
$_orders = $block->getOrders();
$records = '';
$filter_orderstatus = '';
$filter_data_frm = '';
$filter_data_to = '';
if (isset($_GET['records'])) {
  $records = $_GET['records'] != "" ? $_GET['records'] : 10;
}
if (isset($_GET['orderstatus'])) {
  $filter_orderstatus = $_GET['orderstatus'] != "" ? $_GET['orderstatus'] : "";
}
if (isset($_GET['from_date'])) {
  $filter_data_frm = $_GET['from_date'] != "" ? $_GET['from_date'] : "";
}
if (isset($_GET['to_date'])) {
  $filter_data_to = $_GET['to_date'] != "" ? $_GET['to_date'] : "";
}
?>

<?php echo $block->getChildHtml('info');?>

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Sales Order <small>Confirms your sales and triggers</small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Default Grid <small>Orders</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div>
            <form id="search-form-validate" action="<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) ?>"
                  method="get">
              <table cellspacing="0" class="cmsmart_mp_list_table">
                <thead>
                <tr id="cmsmart_mp_tr_heading">
                  <th><span><?php echo __('Shows') ?></span></th>
                  <th><span><?php echo __('Date') ?></span></th>
                  <th><span><?php echo __('Order Status') ?></span></th>
                  <th><span>&nbsp;</span></th>
                </tr>
                </thead>
                <tbody class="cmsmart_mp_body">
                <tr>
                  <td>
                    <select name="records" class="input-text">
                      <option
                          value="10" <?php if ($records == 10) echo 'selected="selected"' ?>>
                        <?php echo __('10') ?>
                      </option>
                      <option
                          value="50" <?php if ($records == 50) echo 'selected="selected"' ?>>
                        <?php echo __('50') ?>
                      </option>
                      <option
                          value="100" <?php if ($records == 100) echo 'selected="selected"' ?>>
                        <?php echo __('100') ?>
                      </option>
                      <option
                          value="200" <?php if ($records == 200) echo 'selected="selected"' ?>>
                        <?php echo __('200') ?>
                      </option>
                    </select>
                  </td>
                  <td>
                                    <span class="cmsmart_mp_td_span">
                                        <?php echo __('From: ') ?>
                                      <input name="from_date" id="special_from_date" class="datepicker"
                                             value="<?php echo $filter_data_frm ?>"/>
                                    </span>
                                    <span class="cmsmart_mp_td_span">
                                      <?php echo __('To: ') ?>
                                      <input name="to_date" id="special_to_date" class="datepicker"
                                             value="<?php echo $filter_data_to ?>"/>
                                    </span>
                  </td>
                  <td>
                    <select name="orderstatus" class="input-text">
                      <option value="">All</option>
                      <option value="canceled">
                        Canceled                        </option>
                      <option value="closed">
                        Closed                        </option>
                      <option value="complete">
                        Complete                        </option>
                      <option value="fraud">
                        Suspected Fraud                        </option>
                      <option value="holded">
                        On Hold                        </option>
                      <option value="payment_review">
                        Payment Review                        </option>
                      <option value="paypal_canceled_reversal">
                        PayPal Canceled Reversal                        </option>
                      <option value="paypal_reversed">
                        PayPal Reversed                        </option>
                      <option value="pending">
                        Pending                        </option>
                      <option value="pending_payment">
                        Pending Payment                        </option>
                      <option value="pending_paypal">
                        Pending PayPal                        </option>
                      <option value="processing">
                        Processing                        </option>
                    </select>
                  </td>
                  <td>
                    <button id="mp-search-btn" class="action submit primary" title="Save" type="submit">
                      <span><?php echo __('Submit') ?></span>
                    </button>
                  </td>
                </tr>
                </tbody>
              </table>
            </form>
          </div>
          <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Order #</th>
                  <th>Address</th>
                  <th>Total</th>
                  <th>Date</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>


              <tbody>
                <?php if ($_orders && count($_orders)): ?>
                    <?php foreach ($_orders as $_order): ?>
                        <tr>
                          <td><?php echo $_order->getRealOrderId() ?></td>
                          <td><?php echo $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                          <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                          <td><?php echo date("F j, Y", strtotime($_order->getCreatedAt())); ?></td>
                          <td><?php echo $_order->getStatusLabel() ?></td>
                          <td><a href="<?php echo $block->getViewUrl($_order) ?>">
                            <span><?php echo __('View Order') ?></span>
                        </a></td>
                        </tr>
                    <?php endforeach;?>    
                <?php endif ?>
              </tbody>
            </table>
            <?php if ($block->getPagerHtml()): ?>
              <?php echo $block->getPagerHtml();?>
            <?php endif; ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  require([
    "jquery",
    "mage/calendar"
  ], function ($) {
    $('.datepicker').datepicker({
          prevText: '&#x3c;zurück', prevStatus: '',
          prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
          nextText: 'Vor&#x3e;', nextStatus: '',
          nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
          monthNames: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni',
            'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
          monthNamesShort: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun',
            'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
          dayNames: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
          dayNamesShort: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
          dayNamesMin: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
          showMonthAfterYear: false,
          dateFormat: 'd/m/yy'
        }
    );

    var dataForm = $('#search-form-validate');
    $('#mp-search-btn').click( function(e) {
      e.preventDefault();
      
      if($("input[name=from_date]").val().trim() == "") {
        $("input[name=from_date]").attr("disabled", "disabled");
      }
      if($("input[name=to_date]").val().trim() == "") {
        $("input[name=to_date]").attr("disabled", "disabled");
      }
      if($("select[name=orderstatus]").val().trim() == "") {
        $("select[name=orderstatus]").attr("disabled", "disabled");
      }

      dataForm.submit();
    });
  });
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "admin_vendor": {}
        }
    }
</script>