<?php $helper = $this->helper('Netbaseteam\Locator\Helper\Data'); ?>
<?php if ($helper->enableCommentFace()): ?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



<div class="col-md-8 col-sm-12 col-xs-12 pull-right plugin">
	<div class="fb-comments" data-width="100%"></div>
</div>
<?php endif ?>