<?php
	$helper = $this->helper('Netbaseteam\Locator\Helper\Data');
?>
<script type="text/javascript">
	require([
		'Cmsmart_Admin_Map'
		    ], function(){		
	});
</script>

<script src="https://maps.google.com/maps/api/js?key=<?php echo $helper->getGeoMapApiKey(); ?>&libraries=places" async defer type="text/javascript"
></script>
<script src="http://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js" type="text/javascript" ></script>