<?php
$helper  = $this->helper('Netbaseteam\Opc\Helper\Data');
// @codingStandardsIgnoreFile
?>
<div id="forgotpassword-popup" style="display: none">
    <div class="cmsmart-opc-forgotpassword">
        <div class="opc-forgot-wrapper">
            <h3>FORGOT PASSWORD</h3>
            <form class="form password forget cmsmart-opc-forgot-form"
                  action="<?php echo $block->getFormActionUrl(); ?>"
                  method="post"
                  id="form-validate"
                  data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset" data-hasrequired="<?php
                echo __('* Required Fields') ?>">
                    <div class="field note"><?php
                        echo __('Please enter your email address below. You will receive a link to reset your password.'); ?></div>
                    <div class="field email required">
                        <label for="email_address"
                               class="label"><span><?php
                                echo __('Email Address') ?></span></label>
                        <div class="control">
                            <input type="email" name="email" alt="email"
                                   id="email_address"
                                   class="input-text forgot-email"
                                   value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>"
                                   data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <?php echo $block->getChildHtml('form_additional_info'); ?>
                </fieldset>
                <div class="forgot-response-message response-success">

                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit"
                                class="forgot-password-submit action submit primary">
                            <span><?php echo __('Submit') ?></span></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: false
            };
            var postUrl = '<?php echo $block->getPostUrl();?>';
            var popup = modal(options, $('#forgotpassword-popup'));

            $(document).off('click touchstart', '.actions-toolbar .remind');
            $(document).on('click touchstart', '.actions-toolbar .remind', function (e) {
                e.preventDefault();
                $('.forgot-response-message').hide();
                $('#forgotpassword-popup').modal('openModal');
            });

            $('.forgot-password-submit').click(function(e){
                e.preventDefault();
                var email = $('.forgot-email').val();

                if (typeof(postUrl) != "undefined") {
                    var sendUrl = postUrl;
                }
                $.ajax({
                    type: "POST",
                    data: {email: email},
                    url: sendUrl,
                    showLoader: true
                }).done(function (response) {
                    if(typeof(response.message != "undefined")){
                        $('.forgot-response-message').html(response.message);
                        $('.forgot-email').val('');
                        $('.forgot-response-message').show();
                    }

                    $(".modal-popup button.action-close").trigger( "click" );
                });
            });
        }
    );
</script>

