<?php
/** @var $block \Cmsmart\Marketplace\Block\Seller\EditProfile */

$helper = $this->helper('Cmsmart\Marketplace\Helper\Data');

$partnerSeller = $block->getSeller();
$partnerLocator = $block->getSellerLocator();
$isLocator = $helper->isLocatorEnable();
$googleApiKey = $helper->getGoogleApiKey();
?>
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Profile Details</h3>
            </div>
        </div>

        <div class="clearfix"></div>
        <form
            action="<?php echo $block->getUrl('marketplace/seller/editProfilePost', ["_secure" => $this->getRequest()->isSecure()]) ?>"
            enctype="multipart/form-data" method="post" data-role="form-profile-validate" data-mage-init='{"validation":{}}'
            id="form-seller-edit-profile">
            <button type="reset" class="action submit primary cmsmart_mp_btn">
                <span><?php echo __('Reset') ?></span>
            </button>
            <button class="action submit primary cmsmart-mp-btn" title="<?php echo __('Save Profile') ?>" type="submit"
                    id="save-btn">
                <span><?php echo __('Save Profile') ?></span>
            </button>
            <?php echo $block->getBlockHtml('formkey') ?>
            <div class="cmsmart-mp-editform">
                <fieldset class="fieldset info cmsmart-mp-fieldset">
                    <legend class="legend"></legend>

                    <div class="field profile">
                        <label class="required"><?php echo __('Shop ID') ?></label>

                        <div class="control">
                            <input type="text" id="shop_id" name="shop_id"
                                   value="<?php echo isset($partnerSeller) ? $partnerSeller['shop_id'] : ''; ?>"
                                   title="<?php echo __('Shop ID') ?>" class="required-entry input-text"/>
                        </div>
                        <div id="shopidavail">
                            <span class="success-msg shopidavailable"><?php echo __('Shop ID Available') ?></span>
                        </div>
                        <div id="shopidnotavail">
                            <span class="error-msg shopidnotavailable"><?php echo __('Shop ID Already Exist') ?></span>
                        </div>
                    </div>
                    <div class="field profile">
                        <label for="shoptitle"><?php echo __('Shop Title') ?></label>

                        <div class="control">
                            <input type="text" id="shop_title" name="shop_title"
                                   value="<?php echo isset($partnerSeller) ? $partnerSeller['shop_title'] : ''; ?>"
                                   title="<?php echo __('Shop Title') ?>" class="input-text"/>
                        </div>
                    </div>
                    <div class="field profile">
                        <label for="shopemail"><?php echo __('Shop Email') ?></label>

                        <div class="control">
                            <input type="text" id="shop_email" name="shop_email"
                                   value="<?php echo isset($partnerSeller) ? $partnerSeller['shop_email'] : ''; ?>"
                                   title="<?php echo __('Shop Email') ?>" class="input-text"/>
                        </div>
                    </div>
                    <div class="field profile">
                        <label for="shop-banner"> <?php echo __('Shop Banner') ?> </label>

                        <span
                            class="control-notification">(<?php echo __("I suggested you should upload 700px X 350px for better look"); ?>
                            )</span>

                        <div class="control">
                            <input type="file" id="shop-banner" name="shop_banner" title="Shop Banner" class="input-text banner"
                                   size="26"/>

                            <div class="profileimage-set">
                                <div class="setimage">
                                    <div id="banner-holder"></div>
                                    <script>
                                        //*
                                        require([
                                            'jquery'
                                        ], function ($) {
                                            $("#shop-banner").on('change', function () {

                                                if (typeof (FileReader) != "undefined") {

                                                    var image_holder = $("#banner-holder");
                                                    image_holder.empty();

                                                    var reader = new FileReader();
                                                    reader.onload = function (e) {
                                                        $("<img />", {
                                                            "src": e.target.result,
                                                            "class": "thumb-image"
                                                        }).appendTo(image_holder);

                                                    };
                                                    image_holder.show();
                                                    reader.readAsDataURL($(this)[0].files[0]);
                                                } else {
                                                    alert("This browser does not support FileReader.");
                                                }
                                            });
                                        });
                                        //*
                                    </script>
                                    <?php
                                    if (isset($partnerSeller)) {
                                        $bannerpic = $partnerSeller['shop_banner'];
                                        $logopic = $partnerSeller['shop_logo'];
                                    }
                                    if (isset($bannerpic)) {
                                        ?>
                                        <img class="cmsmart-banner" alt=" <?php echo __('no image') ?>"
                                             src="<?php echo $helper->getMediaUrl() . 'marketplace/' . (isset($partnerSeller) ? $partnerSeller['shop_banner'] : ''); ?>"/>
                                        <span class="cmsmart-profileimagedelete" title="<?php echo __('Delete') ?>">
                                            <a href="<?php echo $this->getUrl('marketplace/seller/deleteShopBanner', ['_secure' => $this->getRequest()->isSecure()]) ?>">Delete</a>
                                        </span>
                                        <script>
                                            require([
                                                'jquery'
                                            ], function ($) {
                                                $("#shop_banner").on('change', function () {
                                                    $(".cmsmart-banner").remove();
                                                    $(".cmsmart-profileimagedelete").remove();
                                                });
                                            });
                                        </script>
                                        <?php
                                    } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field profile">
                        <label for="shop-logo"> <?php echo __('Shop Logo') ?> </label>

                        <div class="control">
                            <input type="file" id="shop-logo" alt="no image" name="shop_logo"
                                   title="<?php echo __('Shop Logo') ?>" class="input-text banner" size="26"/>

                            <div class="logoimage-set">
                                <div class="setimage">
                                    <div id="logo-holder"></div>
                                    <script>
                                        //*
                                        require([
                                            'jquery'
                                        ], function ($) {
                                            $("#shop-logo").on('change', function () {
                                                if (typeof (FileReader) != "undefined") {

                                                    var image_holder = $("#logo-holder");
                                                    image_holder.empty();

                                                    var reader = new FileReader();
                                                    reader.onload = function (e) {
                                                        $("<img />", {
                                                            "src": e.target.result,
                                                            "class": "thumb-image"
                                                        }).appendTo(image_holder);

                                                    };
                                                    image_holder.show();
                                                    reader.readAsDataURL($(this)[0].files[0]);
                                                } else {
                                                    alert("This browser does not support FileReader.");
                                                }
                                            });
                                        });
                                        //*
                                    </script>
                                    <?php
                                    if (isset($logopic)) {
                                        ?>
                                        <img class="cmsmart-logo"
                                             src="<?php echo $helper->getMediaUrl() . 'marketplace/' . (isset($partnerSeller) ? $partnerSeller['shop_logo'] : ''); ?>"/>
                                        <span class="cmsmart-logoimagedelete" title="<?php echo __('Delete') ?>">
                                            <a href="<?php echo $this->getUrl('marketplace/seller/deleteShopLogo', ['_secure' => $this->getRequest()->isSecure()]) ?>">Delete</a>
                                        </span>

                                        <script>
                                            require([
                                                'jquery'
                                            ], function ($) {
                                                $("#shop-logo").on('change', function () {
                                                    $(".cmsmart-logo").remove();
                                                    $(".cmsmart-logoimagedelete").remove();
                                                });
                                            });
                                        </script>
                                        <?php
                                    } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php if ($isLocator): ?>
                        <fieldset class="fieldset info cmsmart-mp-fieldset">
                            <legend class="legend"><b><?php echo __('Location') ?></b></legend>
                            <div class="table-wrapper-locator">
                                <div class="inner-locator">
                                    <table class="data table table-locator-items" id="locator-table">
                                        <caption class="table-caption"><?php /* @escapeNotVerified */
                                            echo __('Locator') ?></caption>
                                        <thead>
                                        <tr>
                                            <th scope="col" class="col main"><?php /* @escapeNotVerified */
                                                echo __('Main Locator') ?></th>
                                            <th scope="col" class="col address"><?php /* @escapeNotVerified */
                                                echo __('Address') ?></th>
                                            <th scope="col" class="col latitude"><?php /* @escapeNotVerified */
                                                echo __('Latitude') ?></th>
                                            <th scope="col" class="col longitude"><?php /* @escapeNotVerified */
                                                echo __('Longitude') ?></th>
                                            <th scope="col" class="col zipcode"><?php /* @escapeNotVerified */
                                                echo __('Zip Code') ?></th>
                                            <th scope="col" class="col status"><?php /* @escapeNotVerified */
                                                echo __('Status') ?></th>
                                            <th scope="col" class="col actions">&nbsp;</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach ($partnerLocator as $locator): ?>
                                            <?php $locatorId = $locator->getId(); ?>
                                            <tr>
                                                <td><input type="radio" class="input-radio" name="main_location" value="<?php echo $locator->getShopLocation()?>" <?php if($partnerSeller['shop_location'] == $locator->getShopLocation()) echo "checked"?>></td>
                                                <td data-th="<?php echo $block->escapeHtml(__('Address')) ?>"
                                                    class="col address"><?php /* @escapeNotVerified */
                                                    echo $locator->getShopLocation() ?></td>
                                                <td data-th="<?php echo $block->escapeHtml(__('Latitude')) ?>"
                                                    class="col latitude"><?php /* @escapeNotVerified */
                                                    echo $locator->getShopLatitude(); ?></td>
                                                <td data-th="<?php echo $block->escapeHtml(__('Longitude')) ?>"
                                                    class="col longitude"><?php /* @escapeNotVerified */
                                                    echo $locator->getShopLongitude(); ?></td>
                                                <td data-th="<?php echo $block->escapeHtml(__('Zip Code')) ?>"
                                                    class="col zipcode"><?php /* @escapeNotVerified */
                                                    echo $locator->getShopZipcode() ?></td>
                                                <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>"
                                                    class="col status"><?php /* @escapeNotVerified */
                                                    echo $block->getLocatorStatusLabel($locator->getStatus()) ?></td>
                                                <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>"
                                                    class="col actions">
                                                    <a href="<?php echo $this->getUrl("marketplace/locator/edit/id/$locatorId", array('_current' => true)); ?>"
                                                       class="action edit">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Edit') ?></span>
                                                    </a>
                                                    <a href="<?php echo $this->getUrl("marketplace/locator/delete/id/$locatorId", array('_current' => true)); ?>"
                                                       class="action delete">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Delete') ?></span>
                                                    </a>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <td>
                                                <a href="<?php echo $this->getUrl("marketplace/locator/add/", array('_current' => true)); ?>">Add</a>
                                            </td>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </fieldset>
                    <?php else: ?>
                        <div class="field profile">
                            <label for="shop_location"><?php echo __('Shop Location') ?> </label>

                            <div class="control">
                                <input type="text" id="shop_location" name="shop_location"
                                       value="<?php echo isset($partnerSeller) ? $partnerSeller['shop_location'] : ''; ?>"
                                       class="input-text"/>
                            </div>
                        </div>
                    <?php endif;?>
                    <div class="field profile">
                        <label for="shop_description"><?php echo __('Shop Description') ?></label>

                        <div class="control">
                            <textarea type="text" id="shop_description" name="shop_description" title="shop_description"
                                      class="input-text compdesi"><?php echo isset($partnerSeller) ? $partnerSeller['shop_description'] : ''; ?> </textarea>
                        </div>
                        <script>
                            require([
                                'jquery',
                                'mage/adminhtml/wysiwyg/tiny_mce/setup'
                            ], function (jQuery) {

                                var config = '',
                                    editor;

                                jQuery.extend(config, {
                                    settings: {
                                        theme_advanced_buttons1: 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                        'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                                        theme_advanced_buttons2: null,
                                        theme_advanced_buttons3: null,
                                        theme_advanced_buttons4: null,
                                        theme_advanced_statusbar_location: null
                                    },
                                    files_browser_window_url: false
                                });

                                editor = new tinyMceWysiwygSetup(
                                    'shop_description',
                                    config
                                );

                                editor.turnOn();

                                jQuery('#shop_description')
                                    .addClass('wysiwyg-editor')
                                    .data(
                                        'wysiwygEditor',
                                        editor
                                    );
                            });
                        </script>
                    </div>

                    <div class="field profile">
                        <label for="meta_keywords"><?php echo __('Meta Keywords') ?></label>
                        <label
                               class="control-notification">(<?php echo __("Enter Meta Keywords Comma(',') Separated.."); ?>
                            )</label>

                        <div class="control">
                            <textarea type="text" id="meta_keywords" name="meta_keyword" title="Meta Keyword"
                                      class="input-text compdesi"><?php echo isset($partnerSeller) ? $partnerSeller['meta_keyword'] : ''; ?> </textarea>
                        </div>
                    </div>
                    <div class="field profile">
                        <label for="meta_description"><?php echo __('Meta Description') ?></label>

                        <div class="control">
                            <textarea type="text" id="meta_description" name="meta_description" title="Meta Description"
                                      class="input-text"><?php echo isset($partnerSeller) ? $partnerSeller['meta_description'] : ''; ?> </textarea>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="fieldset info cmsmart-mp-fieldset">
                    <legend class="legend"><b><?php echo __('Contact Information') ?></b></legend>
                    <div class="field profile">
                        <label for="facebookid"><?php echo __('Facebook ID') ?> </label>

                        <div class="control">
                            <input type="text" id="facebook_id" name="facebook_id"
                                   value="<?php echo isset($partnerSeller) ? $partnerSeller['facebook_id'] : ''; ?>"
                                   class="input-text"/>
                        </div>
                    </div>

                    <div class="field profile">
                        <label for="twitterid"><?php echo __('Twitter ID') ?> </label>

                        <div class="control">
                            <input type="text" id="twitter_id" name="twitter_id"
                                   value="<?php echo isset($partnerSeller) ? $partnerSeller['twitter_id'] : ''; ?>"
                                   title="twitterid"
                                   class="input-text"/>
                        </div>
                    </div>

                    <div class="field profile">
                        <label for="instagramid"><?php echo __('Instagram ID') ?> </label>

                        <div class="control">
                            <input type="text" id="instagram_id" name="instagram_id"
                                   value="<?php echo isset($partnerSeller) ? $partnerSeller['instagram_id'] : ''; ?>"
                                   class="input-text"/>
                        </div>
                    </div>
                    <div class="field profile">
                        <label for="gplusid"><?php echo __('Google Plus ID') ?> </label>

                        <div class="control">
                            <input type="text" id="gplus_id" name="gplus_id"
                                   value="<?php echo isset($partnerSeller) ? $partnerSeller['gplus_id'] : ''; ?>"
                                   class="input-text"/>
                        </div>
                    </div>
                    <div class="field profile">
                        <label for="youtubeid"><?php echo __('Youtube ID') ?> </label>

                        <div class="control">
                            <input type="text" id="youtube_id" name="youtube_id"
                                   value="<?php echo isset($partnerSeller) ? $partnerSeller['youtube_id'] : ''; ?>"
                                   class="input-text"/>
                        </div>
                    </div>

                    <div class="field profile">
                        <label><?php echo __('Contact Number') ?> </label>

                        <div class="control">
                            <input type="text" id="contact_number" name="contact_number"
                                   value="<?php echo isset($partnerSeller) ? $partnerSeller['contact_number'] : ''; ?>"
                                   title="<?php echo __('Enter Contact Number') ?>" class="input-text"
                                   placeholder="<?php echo __('Enter Contact Number with country code ex: (123) 456-7890') ?>"/>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="fieldset info cmsmart-mp-fieldset">
                    <legend class="legend"><b><?php echo __('Event') ?></b></legend>
                    <div class="field">
                        <label><?php echo __('Event Details') ?></label>

                        <div class="control">
                            <textarea type="text" class="input-text" name="event" id="shop_event"
                                      title="Shop Event"><?php echo isset($partnerSeller) ? $partnerSeller['event'] : ''; ?></textarea>
                        </div>
                        <script>
                            require([
                                'jquery',
                                'mage/adminhtml/wysiwyg/tiny_mce/setup'
                            ], function (jQuery) {

                                var config = '',
                                    editor;

                                jQuery.extend(config, {
                                    settings: {
                                        theme_advanced_buttons1: 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                        'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                                        theme_advanced_buttons2: null,
                                        theme_advanced_buttons3: null,
                                        theme_advanced_buttons4: null,
                                        theme_advanced_statusbar_location: null
                                    },
                                    files_browser_window_url: false
                                });

                                editor = new tinyMceWysiwygSetup(
                                    'shop_event',
                                    config
                                );

                                editor.turnOn();

                                jQuery('#shop_event')
                                    .addClass('wysiwyg-editor')
                                    .data(
                                        'wysiwygEditor',
                                        editor
                                    );
                            });
                        </script>
                    </div>
                </fieldset>
                <fieldset class="fieldset info cmsmart-mp-fieldset">
                    <legend class="legend"><b><?php echo __('Payment Information') ?></b></legend>
                    <div class="field">
                        <label><?php echo __('Payment Details') ?></label>

                        <div class="control">
                            <textarea class="input-text" name="payment_source" id="payment-source" title="payment source"
                                      cols="1"
                                      rows="3"><?php echo isset($partnerSeller) ? $partnerSeller['payment_source'] : ''; ?></textarea>

                        </div>
                    </div>
                </fieldset>
            </div>
        </form>
    </div>
</div>

<div class="loading_overlay"></div>
<?php
$formData = [
    'checkShopIdAjaxUrl' => $block->getUrl('marketplace/seller/checkshopid', ['_secure' => $this->getRequest()->isSecure()])
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "*": {
            "sellerEditProfile": <?php /* @noEscape */ echo $serializedFormData; ?>,
            "admin_vendor": {}
        }
    }
</script>

