<div id="seller-profile-content">
    <div class="cmsmar-mp-title">
        <h3>NEW PRODUCTS</h3>
    </div>
    <?php
    /**
     * Copyright © 2016 Magento. All rights reserved.
     * See COPYING.txt for license details.
     */
    use Magento\Framework\App\Action\Action;

    // @codingStandardsIgnoreFile

    ?>
    <?php
    /**
     * Product list template
     *
     * @var $block \Cmsmart\Marketplace\Block\Seller\Profile\ListProduct
     */
    ?>
    <?php
    $vacation = $block->getVacation();

    $_newProductCollection = $block->getNewProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <?php if($vacation && $vacation['disable_type'] == 'product_disable'):?>
        <div class="message info empty">
            <span>Products has been disabled until shop open again</span>
        </div>
    <?php else:?>
        <?php if (!$_newProductCollection->count()): ?>
        <div class="message info empty">
            <div><?php /* @escapeNotVerified */
                echo __('We can\'t find products matching the selection.') ?></div>
        </div>
    <?php else: ?>
    <?php

    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
        <div class="products wrapper <?php /* @escapeNotVerified */
        echo $viewMode; ?> products-<?php /* @escapeNotVerified */
        echo $viewMode; ?>">
            <?php $iterator = 1; ?>
            <ol class="products list items product-items" id="cmsmart-mp-homepage-new-product">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_newProductCollection as $_product): ?>
                    <?php /* @escapeNotVerified */
                    echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?php /* @escapeNotVerified */
                        echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>

                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */
                                   echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <?php /* @escapeNotVerified */
                            echo $block->getProductPrice($_product) ?>
                            <?php echo $block->getProductDetailsHtml($_product); ?>

                            <div class="product-item-inner">
                                <div
                                    class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div
                                        class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                            echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */
                                                echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>

                                                <?php if($vacation && $vacation['disable_type'] == 'add_to_cart_disable'):?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary"
                                                            disabled>
                                                        <span><?php /* @escapeNotVerified */
                                                            echo $vacation['add_to_cart_label'] ? __($vacation['add_to_cart_label']) : __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else:?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */
                                                            echo $vacation['add_to_cart_label'] ? __($vacation['add_to_cart_label']) : __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif;?>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */
                                                        echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                        echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links"
                                         class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php /* @escapeNotVerified */
                                        echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                        echo $_productNameStripped ?>"
                                           class="action more"><?php /* @escapeNotVerified */
                                            echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php echo ($iterator == count($_newProductCollection) + 1) ? '</li>' : '' ?>
                    <?php if ($iterator == 7) : ?>
                        <?php break; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }


        </script>

    <?php endif; ?>
    <?php endif; ?>
        <script>
            require(['jquery', 'owlCarousel'], function ($) {
                $(document).ready(function ($) {
                    $('#cmsmart-mp-homepage-new-product').owlCarousel({
                        items: 6,
                        itemsCustom: [
                            [0, 1],
                            [360, 1],
                            [600, 2],
                            [800, 3],
                            [992, 3],
                            [1290, 3]
                        ],
                        pagination: true,
                        slideSpeed: 800,
                        addClassActive: true,
                        scrollPerPage: false,
                        touchDrag: true,
                        navigation: true,
                        loop:true,
                        /*autoPlay: 3000,*/
                        navigationText: ["", ""]
                    });
                });
            });
        </script>
    <?php endif;?>

    <div class="cmsmar-mp-title">
        <h3>BEST SELLER</h3>
    </div>


    <?php
    /**
     * Product list template
     *
     * @var $block \Cmsmart\Marketplace\Block\Seller\Profile\ListProduct
     */
    ?>
    <?php
    $_hotProductCollection = $block->getHotProductCollection();
    ?>
    <?php if($vacation && $vacation['disable_type'] == 'product_disable'):?>
        <div class="message info empty">
            <span>Products has been disabled until shop open again</span>
        </div>
    <?php else:?>
        <?php if (!$_hotProductCollection->count()): ?>
        <div class="message info empty">
            <div><?php /* @escapeNotVerified */
                echo __('We can\'t find products matching the selection.') ?></div>
        </div>
    <?php else: ?>
    <?php

    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
        <div class="products wrapper <?php /* @escapeNotVerified */
        echo $viewMode; ?> products-<?php /* @escapeNotVerified */
        echo $viewMode; ?>">
            <?php $iterator = 1; ?>
            <ol class="products list items product-items" id="cmsmart-mp-homepage-hot-product">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_hotProductCollection as $_product): ?>
                    <?php /* @escapeNotVerified */
                    echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?php /* @escapeNotVerified */
                        echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>

                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */
                                   echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <?php /* @escapeNotVerified */
                            echo $block->getProductPrice($_product) ?>
                            <?php echo $block->getProductDetailsHtml($_product); ?>

                            <div class="product-item-inner">
                                <div
                                    class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div
                                        class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                            echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */
                                                echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>

                                                <?php if($vacation && $vacation['disable_type'] == 'add_to_cart_disable'):?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary"
                                                            disabled>
                                                        <span><?php /* @escapeNotVerified */
                                                            echo $vacation['add_to_cart_label'] ? __($vacation['add_to_cart_label']) : __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else:?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */
                                                            echo $vacation['add_to_cart_label'] ? __($vacation['add_to_cart_label']) : __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif;?>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */
                                                        echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                        echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links"
                                         class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php /* @escapeNotVerified */
                                        echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                        echo $_productNameStripped ?>"
                                           class="action more"><?php /* @escapeNotVerified */
                                            echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php echo ($iterator == count($_hotProductCollection) + 1) ? '</li>' : '' ?>
                    <?php if ($iterator == 7) : ?>
                        <?php break; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }


        </script>

    <?php endif; ?>
    <?php endif; ?>
        <script>
            require(['jquery', 'owlCarousel'], function ($) {
                $(document).ready(function ($) {
                    $('#cmsmart-mp-homepage-hot-product').owlCarousel({
                        items: 6,
                        itemsCustom: [
                            [0, 1],
                            [360, 1],
                            [600, 2],
                            [800, 3],
                            [992, 3],
                            [1290, 3]
                        ],
                        pagination: true,
                        slideSpeed: 800,
                        addClassActive: true,
                        scrollPerPage: false,
                        touchDrag: true,
                        navigation: true,
                        loop:true,
                        /* autoPlay: 3000,*/
                        navigationText: ["", ""]
                    });
                });
            });
        </script>
    <?php endif;?>

</div>










