<?php
/** @var $block Cmsmart\Marketplace\Block\Seller\Profile */

$helper = $this->helper('Cmsmart\Marketplace\Helper\Data');
$shopData = $block->getShopData();
$shopID = $this->getRequest()->getParam('shop');
$radKey = 'ref=page_internal';
?>

<div class="about">
    <div>
        <b>About</b>
        <span>
            <a id="mp-profile-view" href="<?php echo $this->getUrl("marketplace/seller/profile/shop/$shopID/about/$radKey", ['_secure' => $this->getRequest()->isSecure()]); ?>">View all</a>
        </span>
    </div>
    <div>
        <div class="contact_number"><?php echo $shopData['contact_number'] ? $shopData['contact_number'] : '';?></div>
    </div>
    <div>
        <div class="shop_location">
            <span>Address</span>
            <iframe width="100%" height="250px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="//maps.google.com/maps?q=<?php echo $shopData['shop_location'] ? $shopData['shop_location'] : '';?>&amp;output=embed"></iframe>
            <br />
        </div>
    </div>
</div>
<div class="shop_facebook">
    <span>Facebook</span>
    <?php echo $block->getFacebookPlugin() ? $block->getFacebookPlugin() : '';?>
</div>
