<?php
if ($this->getRequest()->getParam('about')) {
    echo $this->getLayout()->createBlock("Cmsmart\Marketplace\Block\Seller\Profile")
        ->setTemplate("Cmsmart_Marketplace::seller/about.phtml")->toHtml();
} elseif ($this->getRequest()->getParam('product')) {
    echo $this->getLayout()->createBlock("Cmsmart\Marketplace\Block\Seller\Profile\ListProduct")
        ->setTemplate("Cmsmart_Marketplace::seller/product.phtml")->toHtml();
} elseif ($this->getRequest()->getParam('event')) {
    echo $this->getLayout()->createBlock("Cmsmart\Marketplace\Block\Seller\Profile")
        ->setTemplate("Cmsmart_Marketplace::seller/event.phtml")->toHtml();
} else { ?>
    <?php
    echo $this->getLayout()->createBlock("Cmsmart\Marketplace\Block\Seller\Profile\ListProduct")
        ->setTemplate("Cmsmart_Marketplace::seller/homepage.phtml")->toHtml();
    ?>
<?php } ?>