<?php
$helper = $this->helper('Cmsmart\Marketplace\Helper\Data');
$shopData = $block->getShopData();
?>

<div class="cmsmart-shop-banner">
    <img
        src="<?php echo $helper->getMediaUrl().'marketplace/'.(isset($shopData['shop_banner']) ? $shopData['shop_banner'] : 'no-banner.gif'); ?>"
        alt="<?php echo __('Shop Banner') ?>"
    />
</div>

<div>
    <?php echo $block->getFacebookButton();?>
    <?php echo $block->getTwitterButton();?>
    <?php echo $block->getGooglePlusButton();?>
</div>


