<?php 
	$helper = $this->helper('Netbaseteam\Faq\Helper\Data');
	$faqData = $block->getFaqByTagName();
?>
<div class="faq-require faq-require-category tag-require">
	<h3 class="faq-require-title">
		<i class="line" ></i>
		<span><?php echo __('Tag:  '.$block->getRequireTag()); ?></span>
	</h3>

	<div class="category-body ">
		<?php if ($block->hasFaqByTagName()): ?>
			<?php foreach ($faqData as $faq): ?>
				<div class="panel">
					<div class="panel-heading">
						<h4 class="panel-title" >
							<a href="javascript:void(0);"><?php echo __(strip_tags($faq['question'])); ?></a>
							<i data-icon="icon-plus-1" data-icon-active="icon-minus-1" class="icon-plus-1"></i>
						</h4>
					</div>
					
					<div class="panel-body">
						<div class="panel-content"><?php echo __($faq['answer']); ?></div>
						<div class="more-info">
							
							<?php if ($helper->getShowFaqAthor()): ?>
								<?php if (!empty($faq['author_name'])): ?>
									<span class="author">
										<?php echo __('Created by '.$faq['author_name']);?>
									</span>
								<?php endif ?>
							<?php endif ?>
							<?php if ($helper->getShowFaqCreatedTime()): ?>
								<?php if (!empty($block->getFormatDate($faq))): ?>
									<span class="created-time">
										<?php echo __('on '.$block->getFormatDate($faq));?>
									</span>
								<?php endif ?>
							<?php endif ?>
						</div>		
					</div>
					
				</div>	
			<?php endforeach ?>
			
		<?php else: ?>
			<div class="non-result"><?php echo __('No FAQ Founded'); ?></div>
		<?php endif ?>
	</div>
</div>
<div style="clear: both;"></div>
<script type="text/javascript">
	require([
    'jquery', 
    'jquery/ui',
    'Cmsmart_FAQ'
    ], function($){
    	var faqHeading = $('.faq-require .panel .panel-heading');
    	$('.page-title-wrapper h1.page-title').html('<span>FAQ</span>');
    	$('.messages[data-bind]').eq(1).html('');
    	window.scrollTo(0,100);
    	$(faqHeading).click(function(){
    		var icon = $(this).children().find('i');
            if($(this).hasClass('panel-active')){
               $(this).removeClass('panel-active');
            }else{
                $(this).addClass('panel-active');
            }
            if($(icon).hasClass('fa-plus-square-o')){
                $(icon).removeClass('fa-plus-square-o');
                $(icon).addClass('fa-minus-square-o');
            }else{
                $(icon).removeClass('fa-minus-square-o');
                $(icon).addClass('fa-plus-square-o');
            }   
            $(this).next().fadeToggle('500',function(){
                
            });
    	});
    
    });
  


  
</script>