<?php

namespace Netbaseteam\Navigation\Helper;

use Magento\Store\Model\ScopeInterface;

class Data extends \Magento\Framework\App\Helper\AbstractHelper
{
    /**
     * Check module is enabled
     *
     * @param null $storeId
     * @return mixed
     */
    public function isEnabled($storeId = null)
    {
        return $this->getConfigValue('cmsmart_navigation/general/enable', $storeId);
    }

    /**
     * get store config value by field code
     *
     * @param      $field
     * @param null $storeId
     * @return mixed
     */
    public function getConfigValue($field, $storeId = null)
    {
        return $this->scopeConfig->getValue(
            $field,
            ScopeInterface::SCOPE_STORE,
            $storeId
        );
    }

    public function _getRequest()
    {
        return parent::_getRequest(); // TODO: Change the autogenerated stub
    }
}
