<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if (!$block->isContentMode() || $block->isMixedMode()): ?>
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category_1')->toHtml();?>
    <?php echo $block->getProductListHtml() ?>
<?php endif; ?>
