<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else:?>
    <tr class="<?= /* @escapeNotVerified */ $_code ?>">
        <th <?= /* @escapeNotVerified */ $block->getLabelProperties() ?> scope="row">
            <?php if ($_total->getStrong()):?>
            <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else:?>
            <?= $block->escapeHtml($_total->getLabel()) ?>
            <?php endif?>
        </th>
        <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtml($_total->getLabel()) ?>">
            <?php if ($_total->getStrong()):?>
            <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
            <?php else:?>
            <?= /* @escapeNotVerified */ $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach?>
<tr>
<td class="label">Refund Shipping<div id="shipping_amount_adv"></div></td>
<td>
    <input type="text" name="creditmemo[shipping_amount]" value="<?php echo isset($block->getTotals()['shipping']) ? (int)$block->getTotals()['shipping']['value'] : ''?> " class="input-text admin__control-text not-negative-amount" id="shipping_amount">
</td>
</tr>
<tr>
    <td class="label">Adjustment Refund<div id="adjustment_positive_adv"></div></td>
    <td>
        <input type="text" name="creditmemo[adjustment_positive]" value="" class="input-text not-negative-amount" id="adjustment_positive">
    </td>
</tr>
<tr>
    <td class="label">Adjustment Fee<div id="adjustment_negative_adv"></div></td>
    <td>
        <input type="text" name="creditmemo[adjustment_negative]" value="" class="input-text not-negative-amount" id="adjustment_negative">
        <script>
            require(['prototype'], function(){

            //<![CDATA[
            Validation.addAllThese([
                ['not-negative-amount', 'Please enter a positive number in this field.', function(v) {
                    if(v.length)
                        return /^\s*\d+([,.]\d+)*\s*%?\s*$/.test(v);
                    else
                        return true;
                }]
            ]);

            if ($('shipping_amount')) {
                $('shipping_amount').advaiceContainer = $('shipping_amount_adv');
                unblockSubmit('shipping_amount');
            }
            if ($('adjustment_positive')) {
                $('adjustment_positive').advaiceContainer = $('adjustment_positive_adv');
                unblockSubmit('adjustment_positive');
            }
            if ($('adjustment_negative')) {
                $('adjustment_negative').advaiceContainer = $('adjustment_negative_adv');
                unblockSubmit('adjustment_negative');
            }

            function unblockSubmit(id) {
                $(id).observe('focus', function(event) {
                    if ($$('button[class="scalable update-button disabled"]').size() > 0) {
                        enableElements('submit-button');
                    }
                });
            }
            //]]>

            });
        </script>
    </td>
</tr>

