<?php

	$helper = $this->helper('Netbaseteam\Faq\Helper\Data');
	$categoryData = $block->getCategoryData();

?>

<?php foreach ($categoryData as $category): ?>
	<?php $designData = $block->getCategoryDesignData($category);?>
	<div id="<?php echo 'cate-'.$category['faq_category_id']; ?>" class="category-item" data-design='<?php echo $block->getJsonDesignData($category); ?>'>
		<div class="category-heading">
			<a href="<?php echo $block->getCategoryUrl().'/category/'.$category['faq_category_id']; ?>" title="<?php echo __($category['name']); ?>"
			class="require-category">
				<h3 class="category-title" >
					<?php if (!empty($category['icon'])): ?>
						<i class="line" ></i>
						<i class="fa <?php echo $category['icon'];?>"></i>
					<?php endif ?>
					
					<span><?php echo __($category['name']); ?></span>
				</h3>
				
			</a>
			<div class="cate-description">
				<?php echo __($category['description']); ?>
			</div>
		</div>

		<?php if ($block->hasFaqInCategory($category)): ?>
			<div class="category-body">
				<?php foreach ($block->getFaqByCategory($category['faq_ids']) as $faq): ?>
					<div class="panel">
						<div class="panel-heading">
							<h4 class="panel-title">
								<a href="javascript:void(0);"><?php echo __(strip_tags($faq['question'])); ?></a>
								<i data-icon="icon-plus-1" data-icon-active="icon-minus-1" class="icon-plus-1"></i>
							</h4>
						</div>
						
						<div class="panel-body" >
							<div class="panel-content"><?php echo __($faq['answer']); ?></div>
							<div class="more-info">
								<?php if ($helper->getShowFaqAthor()): ?>
									<?php if (!empty($faq['author_name'])): ?>
										<span class="author">
											<?php echo __('Created by: ');?>
										</span>
									<?php endif ?>
								<?php endif ?>
								<?php if ($helper->getShowFaqCreatedTime()): ?>
									<?php if (!empty($block->getFormatDate($faq))): ?>
										<span class="created-time">
											<?php echo __($faq['author_name'].' on '.$block->getFormatDate($faq));?>
										</span>
									<?php endif ?>
								<?php endif ?>
							</div>		
						</div>
						
					</div>	
				<?php endforeach ?>
			</div>
		<?php endif ?>
	</div>
<?php endforeach ?>
