<?php  
	$helper = $this->helper('Netbaseteam\Faq\Helper\Data');
?>

<div class="contact">
	<div class="primary actions-primary">
		<button id="contact-btn" class="action submit">
			<span><?php echo __('Ask Us Question'); ?></span>
		</button>
	</div>
</div>


<div id="mainform">
	<form id="form" 
	autocomplete="off" method="post" action="<?php echo $block->getFormAction(); ?>">
		<?php echo $block->getBlockHtml('formkey'); ?>
		<input type="hidden" name="reindex_url" value="<?php echo $block->getCallBackUrl(); ?>" />
		<input type="hidden" name="store_ids" value="<?php echo $block->getStoreId(); ?>" />
		<div class="close-btn"></div>
		<h3><?php echo __('Ask Us Question'); ?></h3>
		<p id="returnmessage"></p>
		<label><?php echo __('Name:');?> <span class="validate">*</span></label>
		<input type="text" name="author_name" data-validate="{required:true}" id="name" placeholder="Name"/>
		<label><?php echo __('Email:'); ?> <span class="validate">*</span></label>
		<input type="text" name="author_email" data-validate="{required:true, 'validate-email':true}" id="email" placeholder="Email" />
		<label><?php echo __('Question:'); ?> <span class="validate">*</span></label>
		<textarea id="question" data-validate="{required:true}" placeholder="Enter Your Question..." name="question"></textarea>
		<?php if ($helper->getEnableCaptchaValidate()): ?>
			<?php echo $block->getChildHtml('product.faq.captcha'); ?>
		<?php endif ?>
		<!-- <input type="reset" value="Reset" /> -->
		<input type="submit" id="submit" value="Send Question"/>

	</form>
</div>

<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
   var dataForm = $('#form');
   dataForm.mage('validation', {});
   	$('#contact-btn').click(function(){
   		console.log($("body").scrollTop());
		$('#mainform').show();
	});
   	$( '<span class="validate"> *</span>').insertAfter( "#form .captcha .label span" );
	$('body').click(function(event) {		
		if ($('#form:visible').length&&!$(event.target).closest('#contact-btn').length&&!$(event.target).closest('#form').length) {
			$('#mainform').hide();
		};
	});
	$('#form .close-btn').click(function(){
		$('#mainform').hide();
	});

});
</script>
