<?php 
	$helper = $this->helper('Netbaseteam\Faq\Helper\Data');
	$mostFaqData = $block->getMostFaqData();
?>
<h3 class="most-faq-title"><i class="icon-edit"></i><?php echo __('Most FAQ') ?></h3>
<p>How to manage your account and it's features.</p>
<div class="most-faq-main">
	<?php if ($block->hasMostFaq()): ?>
		
		<?php foreach ($mostFaqData as $mostFaq): ?>
			<div class="panel">
				<div class="panel-heading">
					<h4 class="panel-title" >
						<a href="javascript:void(0);"><?php echo __(strip_tags($mostFaq['question'])); ?></a>
						<i data-icon="icon-plus-1" data-icon-active="icon-minus-1" class="icon-plus-1"></i>
					</h4>
				</div>
				
				<div class="panel-body">
					<div class="panel-content"><?php echo __($mostFaq['answer']); ?></div>
					<div class="more-info">
						<?php if ($helper->getShowFaqAthor()): ?>
							<?php if (!empty($mostFaq['author_name'])): ?>
								<span class="author">
									<?php echo __('Created by: '.$mostFaq['author_name']);?>
								</span>
							<?php endif ?>
						<?php endif ?>

						<?php if ($helper->getShowFaqCreatedTime()): ?>
							<?php if (!empty($block->getFormatDate($mostFaq))): ?>
								<span class="created-time">
									<?php echo __('on '.$block->getFormatDate($mostFaq));?>
								</span>
							<?php endif ?>
						<?php endif ?>
					</div>		
				</div>
				
			</div>	
		<?php endforeach ?>
		
	<?php else: ?>
		<h4 class="non-most-faq"><?php echo __('No Most FAQ Result'); ?></h4>
	<?php endif ?>
</div>
<div style="clear: both;"></div>
