<?php  
	$helper = $this->helper('Netbaseteam\Blog\Helper\Data');
	$metaInfo = $block->getMetaInfo();
	$categoryInfo = $block->getCategoryInfo();
	$preUrl = $helper->getPreBlogUrl();
?>
<?php if ($metaInfo['tag']): ?>
	<div class="tags">
		<span><?php echo $metaInfo['tag'] ?></span>
	</div>
<?php endif ?>
	<div class="name">
		<span><?php echo $this->getPost()->getTitle(); ?></span>
	</div>
<div class="meta-info">
	<?php if ($metaInfo['creation_time']): ?>
		<div class="creation-time">
			<i class="fa fa-clock-o"></i>
			<span><?php echo __($metaInfo['creation_time']); ?></span>		
		</div>
	<?php endif ?>
	<?php if ($metaInfo['author_name']): ?>
		<div class="author-name">
			<i class="fa fa-user"></i>
			<span><?php echo __($metaInfo['author_name']); ?></span>
		</div>
	<?php endif ?>

	<?php if ($metaInfo['author_email']): ?>
		<div class="author-email">
			<i class="fa fa-envelope"></i>
			<span><?php echo __($metaInfo['author_email']); ?></span>	
		</div>
	<?php endif ?>

	<?php if (count($categoryInfo)>0): ?>
		<div class="category-name">
			<i class="fa fa-folder"></i>
			<?php foreach ($categoryInfo as $key => $category): ?>
				<a href="<?php echo $preUrl.'/'.$category['identifier']; ?>"><?php echo __($category['category_name'] );?></a>
			<?php endforeach ?>
		</div>
	<?php endif ?>

	<?php if ($metaInfo['num_comments']): ?>
		<div class="num_comments">
			<i class="icon-comment-7"></i>
			<span><?php echo __($metaInfo['num_comments']); ?></span>
			<?php if($metaInfo['num_comments'] <2 ):?>
				<span>Comment</span>
			<?php else: ?>
				<span>Comments</span>
			<?php endif; ?>
		</div>
	<?php endif ?>

	

</div>

<div class="content">
	<div class="fluid-content">
		<?php echo __($block->getPostContent()); ?>
	</div>		
</div>	
