<?php
use Magento\Framework\App\Action\Action;
?>

<?php
	$productList = $block->getListProduct();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	$image = 'category_page_grid';
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$pos = null;
	$viewMode = 'grid';
	if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
?>

<?php if ($block->hasRelatedProduct()): ?>
	<div class="block-title">
		<h2><strong>Related Products</strong></h2>
	</div>

	<div class="block-content">
		<div class="products-grid">
			<ol class="product-items">
				<?php foreach ($productList as $key => $product): ?>
					<li class="product-item">
						<div class="product-item-info">
							<a href="<?php echo $product->getProductUrl(); ?>" class="product-item-photo" title="<?php echo __($product->getName()); ?>">
								<?php
									$productImage = $block->getImage($product, $image);
									echo $productImage->toHtml();
								?>
							</a>

							<div class="product-item-details">
								<?php
		                            $_productNameStripped = $block->stripTags($product->getName(), null, true);
		                        ?>
		                        <strong class="product name product-item-name">
		                            <a class="product-item-link"
		                               href="<?php  echo $product->getProductUrl() ?>">
		                                <?php  echo $_helper->productAttribute($product, $product->getName(), 'name'); ?>
		                            </a>
		                        </strong>
		                        <?php echo $block->getReviewsSummaryHtml($product, $templateType, true); ?>
		                        <?php echo $block->getProductPrice($product); ?>


		                        <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
							        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
							            <?php if ($product->isSaleable()): ?>
							                <?php $postParams = $block->getAddToCartPostParams($product); ?>
							                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
							                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
							                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
							                                            <?php echo $block->getBlockHtml('formkey')?>
							                        <button type="submit"
							                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
							                                                    class="action tocart primary">
							                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
							                        </button>
							                    </form>
							            <?php else: ?>
							                <?php if ($product->getIsSalable()): ?>
							                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
							                <?php else: ?>
							                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
							                <?php endif; ?>
							            <?php endif; ?>
							        </div>

							        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
							            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
							                <a href="#" class="action towishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
							                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($product); ?>'
							                                           data-action="add-to-wishlist"
							                                           role="button">
							                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
							            	</a>
							            <?php endif; ?>
							            <?php
							                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
							            ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($product); ?>'
                                       role="button">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                    </a>
                                </div>
                            </div>
	





								 
							</div>
						</div>
					</li>
				<?php endforeach ?>
				
			</ol>
		</div>
	</div>
<?php endif ?>


