<?php $_locators = $block->getSellerLocator();?>
<?php echo $block->getChildHtml('info'); ?>

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Manage Locators <small>All your store locations</small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Default Grid <small>Locators</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Address</th>
                  <th>Latitude</th>
                  <th>Longitude</th>
                  <th>Zip Code</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>

              <tbody>
                <?php if ($_locators && count($_locators)): ?>
                    <?php foreach ($_locators as $locator): ?>
                    <?php $locatorId = $locator->getId(); ?>
                    <tr>
                      <td><?php echo $locator->getShopLocation() ?></td>
                      <td><?php echo $locator->getShopLatitude(); ?></td>
                      <td><?php echo $locator->getShopLongitude(); ?></td>
                      <td><?php echo $locator->getShopZipcode() ?></td>
                      <td><?php echo $block->getLocatorStatusLabel($locator->getStatus()) ?></td>
                      <td>
                        <a href="<?php echo $this->getUrl("marketplace/locator/edit/id/$locatorId", array('_current' => true)); ?>">
                                                    <span><?php /* @escapeNotVerified */
                                                      echo __('Edit') ?></span>
                        </a>
                        <a href="<?php echo $this->getUrl("marketplace/locator/delete/id/$locatorId", array('_current' => true)); ?>">
                                                    <span><?php /* @escapeNotVerified */
                                                      echo __('Delete') ?></span>
                        </a>
                      </td>
                    </tr>
                    <?php endforeach;?>
                <?php endif ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    require(['jquery', 'datatables'], function($){
        $(document).ready(function() {
            $('#datatable').DataTable();
            <?php if(!count($_locators)):?>
              $('#datatable_paginate').remove();
            <?php endif;?>
        });
    });
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "admin_vendor": {}
        }
    }
</script>