<?php
	$helper = $this->helper('Cmsmart\Marketplace\Helper\Data');
	$googleApiKey = $helper->getGoogleApiKey();
?>
<div class="map-box-container col-sm-8 col-xs-12 pull-right">
	<div id="map-canvas" class="googlemap">

	</div>

	<div id="pano"></div>
</div>

<script src="https://maps.google.com/maps/api/js?v=3.exp&key=<?php echo $googleApiKey;?>&libraries=places" async defer type="text/javascript"
></script>

<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js" type="text/javascript" ></script>
