<?php
$helper = $this->helper('Cmsmart\Marketplace\Helper\Data');
$distanceUnit = $helper->getDistanceUnit();
$request = $this->getRequest()->getParams();
if(isset($request['shop_title']) || isset($request['zip_code'])) {
    $typeRequest = 'area';
} else {
    $typeRequest = 'distance';
}
?>
<div class="search-box">
    <div class="search-button col-xs-12">
        <div class="search-distance pull-left search-tab <?php echo $typeRequest == 'distance' ? 'active' : ''?>">
            <span><?php echo __('Search by Distance'); ?></span>
        </div>
        <div class="search-area pull-left search-tab <?php echo $typeRequest == 'area' ? 'active' : ''?>">
            <span><?php echo __('Search by Area'); ?></span>
        </div>
    </div>
    <div class="search-content col-xs-12">
        <div class="container-search">
            <form class="search-distance" id="form-search-distance"
                  action="<?php echo $block->getSearchAction(); ?>" method="post">
                <div class="search-by-distance <?php echo $typeRequest == 'distance' ? '' : 'hide'?>">
                    <div class="form-inline col-full form-group padding-right padding-left">


                        <div class=" form-group col-md-4 col-sm-4 col-xs-12">
                            <input id="auto-fill" type="text" name="address"
                                   placeholder="<?php echo __('Enter a Location...'); ?>" autocomplete="off"
                                   class="input-search-distance input-sm"/>
                        </div>

                        <div class="form-group col-md-4 col-sm-4 col-xs-12 slider-range-min">
                            <div id="slider-range-min"
                                 class="slider-range-bar slider-range ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all">
                            </div>

                            <?php if ($distanceUnit == 'mile'): ?>
                                <span class="show-unit slider-range-amount" range-data="1609">
										<?php echo __('1 Mile'); ?>
									</span>
                            <?php else: ?>
                                <span class="show-unit slider-range-amount" range-data="1000">
										<?php echo __('1 Km'); ?>
									</span>
                            <?php endif ?>
                        </div>

                        <div class="form-group col-sm-3 col-xs-12 pull-right button-box text-right">
                            <div class="btn-wap">
                                <button class="btn-reset-search-distance action primary"
                                        title="<?php echo __('Reset'); ?>" type="reset">
                                    <span><?php echo __('Reset'); ?></span>
                                </button>
                                <button class="btn-search-distance action primary" title="<?php echo __('Search'); ?>" type="submit" disabled="disabled">
                                    <span><?php echo __('Search'); ?></span>
                                </button>
                            </div>
                        </div>

                    </div>
                </div>
            </form>

            <div class="search-by-area <?php echo $typeRequest == 'area' ? '' : 'hide'?>">
                <form class="search-area" id="form-search-area" action="<?php echo $block->getSearchAction(); ?>"
                      method="post">
                    <div class="form-group col-sm-4 col-xs-12 padding-right padding-left">
                        <input type="text" name="shop_title" title="Store Name" placeholder="Store Name"
                               class="input-search-area form-control" value="<?php echo isset($request['shop_title']) ? $request['shop_title'] : '' ?>"/>
                    </div>

                    <div class="form-group col-sm-4 col-xs-12  padding-right padding-left">
                        <input type="text" name="shop_zipcode" title="<?php echo __('Zip Code'); ?>"
                               placeholder="<?php echo __('Zip Code'); ?>" class="input-search-area form-control" value="<?php echo isset($request['shop_zipcode']) ? $request['shop_zipcode'] : '' ?>">
                    </div>

                    <div
                        class="form-group col-sm-4 col-xs-12 pull-right text-right padding-right padding-left btn_locator">
                        <button class="btn-reset-search-area action primary" title="<?php echo __('Reset'); ?>"
                                type="reset">
                            <span><?php echo __('Reset'); ?></span>
                        </button>
                        <button class="btn-search-area action primary" title="<?php echo __('Search'); ?>"
                                type="submit" disabled="disabled">
                            <span><?php echo __('Search'); ?></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

