<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
$helper_config = $this->helper('Netbase\Sun\Helper\Data');
$custom_search_border_radius = $helper_config->getConfig('sun_settings/header/custom_search_border_radius');
$custom_icon_search = $helper_config->getConfig('sun_settings/header/custom_icon_search');
$fontsize_icon_search = $helper_config->getConfig('sun_settings/header/fontsize_icon_search');
$header_type = $helper_config->getConfig('sun_settings/header/header_type');  
?>
<div class="ajaxsearch_ext">  
		<span class="toggle-search"></span>
        <form style="border-radius:<?php echo $custom_search_border_radius; ?>" class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="form-search field search"> 
                <div class="control"> 
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php if($header_type =="eleven"){ echo __('Search...');} else {echo __('What are you looking for...');} /* @escapeNotVerified */  ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-expanded ="true"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                    <div class="actions">
                        <button type="submit"
                                title="<?php echo $block->escapeHtml(__('Search')) ?>"
                                class="action search">
                            <span><i style ="font-size:<?php echo $fontsize_icon_search; ?>" class="icon-<?php echo $custom_icon_search;?>"></i></span>
                        </button>
                    </div>
                </div>
            </div> 
        </form>
   
</div>
