<?php
	$helper = $this->helper('Netbaseteam\Locator\Helper\Data');
	
?>
<div class="map-box-container col-md-12 col-sm-12 col-xs-12 pull-right">
		<div id="map-canvas" class="googlemap">
		
		</div>
	<div id="pano"></div>
</div>

<script type="text/javascript">
	require([
		'Cmsmart_Localtor'
		    ], function(){
			    
				
		    });
</script>

<script src="https://maps.google.com/maps/api/js?key=<?php echo $helper->getGeoMapApiKey(); ?>&libraries=places" async defer type="text/javascript"
></script>
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js" type="text/javascript" ></script>
