<?php
	$id = $this->getRequest()->getParam('megamenu_id');
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$model = $objectManager->create('Cmsmart\Megamenu\Model\Megamenu');
	$catalogSession = $objectManager->create('Magento\Catalog\Model\Session');
	$model->load($id);	
	
	$catalogSession->setVerCatIds($model->getLeftPgridCats());
?>
		
<div data-ui-id="megamenu-edit-tab-image-fieldset-element-form-field-left-pgrid-box-title" class="admin__field field field-left_pgrid_cats">
	<label data-ui-id="megamenu-edit-tab-image-fieldset-element-text-left-pgrid-box-title-label" for="megamenu_main_top_pgrid_cats" class="label admin__field-label"><span>Select Categories</span></label>
	<div class="admin_field-control control">
		<input type="text" class=" input-text admin__control-text" title="Select Categories" value="<?php echo $model->getLeftPgridCats(); ?>" name="left_pgrid_cats" id="left_pgrid_cats">                            
		<img id="ver_cat_select" class="v-middle rule-chooser-trigger" src="<?php echo $this->getViewFileUrl('Cmsmart_Megamenu/images/select.gif'); ?>">
	</div>
	<!-- *** grid select product in checkbox *** -->
	<div id="nb_top_select_cat">
		<div id="vermenu_CatGrid" style="display: none; float: left; clear: both;margin-left: 253px;margin-top: 20px;">
		<?php
		echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')
				->setTemplate('Cmsmart_Megamenu::renderer/form/ver_categories_tree.phtml')->toHtml();
		?>
		</div>
	</div>
</div>

<script type="text/javascript">
	Event.observe('ver_cat_select', 'click', function() {	
		$('vermenu_CatGrid').toggle();
	});
	
	function myVerCatSelect(myEl){
	var vfind = myEl.value;
	var cid_arr = $('left_pgrid_cats').value.split(",");
	if(!myEl.checked){
		var aryCatFound = cid_arr.filter(function(value) { return value != vfind });
		str = aryCatFound.toString();
		str = str.replace(/(^[,\s]+)|([,\s]+$)/g, '');
	} else {
		str = $('left_pgrid_cats').value + "," + vfind;
		str = str.replace(/(^[,\s]+)|([,\s]+$)/g, '');
	}
	$('left_pgrid_cats').value = str;
}
</script>
