<?php
/**
* Copyright © 2016 SW-THEMES. All rights reserved.
*/
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
	$showWishlist = true;
    $showCompare = true;
	$_helper = $this->helper('Netbase\Product\Helper\Data');
	$config = $_helper->getConfig("pro_new/general");
	$categories = explode(',', $config['categories']);
	$attributeId = $config['attribute_code'];
	$title = $_helper->getTitle('pro_new/general/title');
	$currentSymbol = $_helper->getCurrencySymbol();
	$banner = $_helper->getBanner('pro_new/general/banner');

	$tabs = $_helper->getAllTabs('pro_new/general/categories','new-tab-');	 
?>
<section id ="newproduct-amazon" class="home-product-tab-amazon newproduct-amazon new-product home-product-tab animation-element slide-left"> 
	<div class="inner-block">
		<div class="row">
			<div class="home-product-title col-md-12 col-xs-12">
				<div class="row">
					<div class="title-left col-md-6 col-xs-12">
						<h3><?php echo $title; ?></h3>  
					</div>

					<div class="home-product-tab-title col-md-6 col-xs-12"> 
						<ul class="tabs tabs-new">
							<?php echo $tabs; ?>
						</ul> 
						<div class="navslider-tabs navslider-new">
							<a class="prev" href="#"><i class='icon-angle-circled-left'></i></a>
							<a class="next" href="#"><i class='icon-angle-circled-right'></i></a>
						</div> 
					</div> 
				</div>
			</div> 
			<div class="col-md-12 col-xs-12 home-product-tab-content">
				<?php
					$j = 1; foreach($categories as $categoryId): 
					//echo $categoryId;
					
					$productCollection = $block->getProductCollection($categoryId);
				?>
				<div class="navslider">
					<a class="prev" href="#"><i class='icon-left-open-big'></i></a>
					<a class="next" href="#"><i class='icon-right-open-big'></i></a>
				</div>
				<div id="new-tab-<?php echo $j; ?>" class="tab-content <?php if($j == 3){ echo 'show loaded';} ?>" data-rev = "<?php echo $categoryId; ?>">  
					<?php if ($j==3): ?> 
						<div class="home-product-slider products-grid nb-list">
							
							<?php
								$i=0; foreach ($productCollection as $_product):
							?>
							<div class="item">
								<div class="product-item-info" data-container="product-grid">
									<?php      
										$originalPrice = $_product->getPrice();  //200 
										$specialPrice = $_product->getSpecialPrice();  
									?>
									<?php if(($specialPrice)&&($specialPrice <= $originalPrice)){?>	
										<div class="sale">
											<span> 
												<?php
													$saleof= abs(($specialPrice/($originalPrice))*100-100);
													echo '- ';    
													print_r(floor($saleof));
													echo '%'; 
												?>									 
											</span> 
										</div>
									<?php } ?>
						            <?php
									    $image = 'category_page_grid' or 'category_page_list';
									    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
									    $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(160)->getUrl();
									?>
						 			<div class="item-top">
							 			<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
											<img alt="" src="<?php echo $productImage; ?>" />
										</a> 
										<div class="actions"> 
										<div class="quickview actions-all">
											<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
												->setData('pid', $_product->getId())
												->setTemplate("Cmsmart_Quickview::quickview.phtml")->toHtml();?>
										</div>

										<?php
											$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
										?>
										<div class="tocompare-div actions-all">
											<a href="#"
											   class="action tocompare"
											   title="<?php echo __('Add To Compare'); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
											   role="button">
											   <i class="fa fa-refresh" aria-hidden="true"></i>
											</a>
										</div>
										<?php if ($showWishlist || $showCompare): ?>
											<?php
											$objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
											$objBlock = $objectManagerr->get('\Magento\CatalogWidget\Block\Product\ProductsList');
											?>
											<div class="actions-secondary actions-all" data-role="add-to-links">
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
													<a href="#"
													   data-post='<?php /* @escapeNotVerified */ echo $objBlock->getAddToWishlistParams($_product); ?>'
													   class="action towishlist" data-action="add-to-wishlist"
													   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
														<span><i class='icon-heart-1'></i></span>
													</a>
												<?php endif; ?> 
											</div>
										<?php endif; ?> 
	                            </div>
		                            </div>
									<div class="product details product-item-details">
										<div class="inner-product">
											<a title="<?php echo $_product->getName(); ?>" href="<?php echo $_product->getProductUrl() ?>" class="product-item-link">
								                <?php echo $_product->getName(); ?>
								            </a>
											<?php $ratingSummary = $this->getRatingSummary($_product);  ?>
											<div class="product-reviews-summary">
											    <div class="rating-summary">
											        <span class="label"><span><?php /* @escapeNotVerified */ echo __('Rating') ?>:</span></span>
											        <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $ratingSummary; ?>%">
											            <span style="width:<?php /* @escapeNotVerified */ echo $ratingSummary ? $ratingSummary: '0'; ; ?>%"></span>
											        </div>
											    </div>
											</div> 
											<?php
												$originalPrice = $_product->getData('price')+0;
												$finalPrice = $_product->getData('special_price')+0; 
											?>
											<div class="price-home <?php if($finalPrice){ echo 'price-sale'; } ?>">
												<?php 
													if ($finalPrice) {
														echo "<span class='special'>".$currentSymbol.$finalPrice.'.00'."</span>";
													};
													if ($originalPrice) {
														echo "<span class='normal'>".$currentSymbol.$originalPrice.'.00'."</span>";
													}; 
												?>
											</div> 
											<div class="actions-primary">
	                                            <?php if ($_product->isSaleable()): ?>
	                                                <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
	                                                    <button class="action tocart primary one"
	                                                            data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product) ?>"}}'
	                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
	                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
	                                                    </button>
	                                                <?php else: ?>
	                                                    <?php
	                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
	                                                        
	                                                        $postDatas = $_helper->getAddToCartPostParams($_product);
	                                                        $postData = json_encode($postDatas);
	                                                    ?>
	                                                    <button class="action tocart primary two"
	                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
	                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
	                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
	                                                    </button>
	                                                <?php endif; ?>
	                                            <?php else: ?>
	                                                <?php if ($_product->getIsSalable()): ?>
	                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
	                                                <?php else: ?>
	                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
	                                                <?php endif; ?>
	                                            <?php endif; ?>
	                                        </div>
							            </div>
							        </div>
						        </div> 
						    </div>
							<?php
								if ($i == 8) {
									break;
								}
								$i++; endforeach;
							?>
						</div>
					<?php endif; ?>
				</div>
				<?php $j++; endforeach; ?>
			</div>
		</div>
	</div>
</section>

<script type="text/javascript">
	//Home product tab
	require([
     'jquery',
     'jquery/ui'
    ],
    function($, tabs) {
        $(document).ready(function(){
        	$('#newproduct-amazon ul.tabs li').removeClass('current');
			$("#newproduct-amazon li[data-tab='new-tab-3']").addClass('current'); 
			$('#newproduct-amazon ul.tabs li').click(function(event){
				var tab_id = $(this).attr('data-tab');
				var cat_id = $(this).attr('data-rev');
				$('#newproduct-amazon ul.tabs li').removeClass('current');
				$('#newproduct-amazon .tab-content').removeClass('show');
				$('#newproduct-amazon .tab-content').removeClass('current');
		
				$(this).addClass('show');
				$("#newproduct-amazon div[data-rev='"+cat_id+"']").addClass('show');
				$("#newproduct-amazon li[data-rev='"+cat_id+"']").addClass('current');
				var hasloaded = !$("#newproduct-amazon div[data-rev='"+cat_id+"']").hasClass('loaded');

				if (hasloaded) {
					var param = {
						'categoryId':  cat_id,
						'type' : 'newproduct',
						'home' : 'amazon',
					};
					$.ajax({
						url: "<?php echo $this->getUrl('product/index/index') ?>",
						data: param,
						type: "POST",
						showLoader: true,
						dataType: 'json'
					}).done(function (data) { 
						var html = $(data.cate_view);
						$("#newproduct-amazon div[data-rev='"+cat_id+"']").html(html);
					});
				} 
				$("#newproduct-amazon div[data-rev='"+cat_id+"']").addClass('loaded');
			})
		});
    }); 

    //Product owl carousel slider
    require(['jquery','owlCarousel'], function($) {
		jQuery(document).ready(function() {		
			$('.new-product div.products-grid').owlCarousel({
				items: 6,
				itemsCustom: [ 
					[0, 1], 
					[480, 2], 
					[768, 3],  
					[992, 3],
					[1024, 4],  
					[1210, 5] 
				],
				pagination: false,
				slideSpeed : 800,
				addClassActive: true,
				scrollPerPage: false,
				touchDrag: false,
				afterAction: function (e) {
					if(this.$owlItems.length > this.options.items){
						$('.new-product .navslider').show();
					}else{
						$('.new-product .navslider').hide();
					}
				}
				//scrollPerPage: true,
			});
			$('.new-product .navslider .prev').on('click', function(e){
				e.preventDefault();
				$('.new-product div.products-grid').trigger('owl.prev');
			});
			$('.new-product .navslider .next').on('click', function(e){
				e.preventDefault();
				$('.new-product div.products-grid').trigger('owl.next');
			});
			$('.tabs-new').owlCarousel({
				items: 6,
				itemsCustom: [ 
					[320, 2], 
					[480, 4],  
					[768, 4], 
					[1024, 4], 
					[1210, 4],
					[1440, 6]
				],
				pagination: false,
				slideSpeed : 800,
				addClassActive: true,
				scrollPerPage: false,
				touchDrag: true,
				autoWidth:true,
				afterAction: function (e) {
					if(this.$owlItems.length > this.options.items){
						$('.navslider-new').show();
					}else{
						$('.navslider-new').hide();
					}
				}
				//scrollPerPage: true,
			});
			$('.navslider-new .prev').on('click', function(e){
				e.preventDefault();
				$('.tabs-new').trigger('owl.prev');
			});
			$('.navslider-new .next').on('click', function(e){
				e.preventDefault();
				$('.tabs-new').trigger('owl.next');
			});
		}); 
    });   
</script>