<?php
	$id = $this->getRequest()->getParam('productvideo_id');
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$model1 = $objectManager->create('Netbaseteam\Productvideo\Model\Productvideo');
	$catalogSession = $objectManager->create('Magento\Catalog\Model\Session');
	$model1->load($id);	
	
	$catalogSession->setVrelate($model1->getVidRelate());
?>
		
<div class="admin__field field field-left_pgrid_products">
	<label class="label admin__field-label"><span><?php echo __('Related video') ?></span></label>
	<div class="admin_field-control control">
		<input type="text" class=" input-text admin__control-text" value="<?php echo $model1->getVidRelate(); ?>" name="vid_relate" id="vid_relate">
	</div>
	
	<!-- *** grid select product in checkbox *** -->
	<div id="nb_top_select_vrelateids">
		<div id="relate_menu_Grid">
		<?php
			echo $this->getLayout()->createBlock('Netbaseteam\Productvideo\Block\Adminhtml\Pgrid\Relate')
					->toHtml(); 
		?>
		</div>
	</div>
</div>

<script type="text/javascript">
	function myRelateFunctionSelect(myEl){
		var vfind = myEl.value;
		var vid_arr = $('vid_relate').value.split(",");
		if(!myEl.checked){
			var aryWithoutFound1 = vid_arr.filter(function(value) { return value != vfind });
			str1 = aryWithoutFound1.toString();
			str1 = str1.replace(/(^[,\s]+)|([,\s]+$)/g, '');
		} else {
			str1 = $('vid_relate').value + "," + vfind;
			str1 = str1.replace(/(^[,\s]+)|([,\s]+$)/g, '');
		}
		
		$('vid_relate').value = str1;
	}
</script>
