<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
$moduleHelper = $this->helper('Netbaseteam\Navigation\Helper\Data');
$displayMode = $moduleHelper->getConfigValue('cmsmart_navigation/general/display_mode');
?>

<ol class="items cmsmart_navigation_items">
    <?php foreach ($filterItems as $filterItem): ?>
        <?php
        $filter = $filterItem->getFilter();
        $attributeModel = $filter->getData('attribute_model');
        $inputName = $filter->getRequestVar();
        $requestValue = $block->getRequest()->getParam($inputName);
        $requestArray = $requestValue ? explode(',', $requestValue) : [];
        $url = in_array($filterItem->getValue(), $requestArray) ? $filterItem->getRemoveUrl() : $filterItem->getUrl();
        ?>
        <li class="item">
            <?php if($attributeModel && $attributeModel->getFrontendInput() == 'price'): ?>
                <?php
                    $productCollection = $filter->getLayer()->getProductCollection();
                    $productCollectionClone = $productCollection->getCollectionClone();
                    $collection = $productCollectionClone
                        ->removeAttributeSearch(['price.from', 'price.to']);

                    $min = $collection->getMinPrice();
                    $max = $collection->getMaxPrice();

                    list($from, $to) = $requestValue ? explode('-', $requestValue) : [$min, $max];
                ?>
                <span id="cmsmart_nav_price_attribute">
                    <li id="cmsmart_nav_price_slider"></li>
                    <li class="cmsmart_nav_price_input">
                        <span>
                            <input class="input-field min-value" type="text" id="slider_min"  placeholder="From"
                                   value="<?php if (!empty($min)) echo $min ?>" style="width: 33%"/>
                            <input class="input-field max-value" type="text" id="slider_max"  placeholder="To"
                                   value="<?php if (!empty($max)) echo $max ?>" style="width: 33%; float: right"/>
                        </span>
                    </li>
                </span>
                <script type="text/x-magento-init">
                    {
                        "#cmsmart_nav_price_attribute": {
                            "Netbaseteam_Navigation/js/price/slider": {
                                "selectedFrom": <?php echo $from ?>,
                                "selectedTo": <?php echo $to ?>,
                                "minValue": <?php echo $min ?>,
                                "maxValue": <?php echo $max ?>,
                                "priceFormat": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Tax\Helper\Data')->getPriceFormat($block->getStore()); ?>,
                                "ajaxUrl": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($filterItem->getUrl()) ?>
                            }
                        }
                    }
                </script>
                <?php break; ?>
            <?php elseif($displayMode == 1): ?>
				<?php if ($filterItem->getCount() > 0): ?>
                    <a href="<?php echo $block->escapeUrl($url) ?>">
                        <?php if($attributeModel && $attributeModel->getFrontendInput() == 'multiselect'): ?>
                            <input type="checkbox" <?php echo in_array($filterItem->getValue(), $requestArray) ? 'checked="checked"' : ''  ?> />
                        <?php endif; ?>
						<?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                        <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                            <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
								<?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                        <?php endif; ?>
					</a>
                <?php else:?>
                    <?php if($attributeModel && $attributeModel->getFrontendInput() == 'multiselect'): ?>
                        <input type="checkbox" disabled="disabled" />
                    <?php endif; ?>
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
							<?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
<?php if ($displayMode == 2): ?>
    <ol class="items">
        <li>
            <select class="cmsmart_dropdown_filter">
                <option value="<?php echo $block->escapeUrl($this->getClearUrl()) ?>">Choose Option...</option>
                <?php foreach ($filterItems as $filterItem):
                    $disabled = ($filterItem->getCount() == 0) ? ' disabled' : "";
                    $url = $block->escapeUrl($filterItem->getUrl());
                    $label = $filterItem->getLabel();
                    if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()) {
                        $label .= ' <span class="count">(' . $filterItem->getCount() . ')</span>';
                    }
                    ?>
                    <option value="<?php echo $url ?>" <?php echo $disabled ?>><?php echo $label ?></option>
                <?php endforeach ?>
            </select>
        </li>
    </ol>

    <script>
        require(["jquery"], function ($) {
            $(document).ready(function () {
                var parentBody = window.parent.document.body;
                $('#filter-by-Price .cmsmart_dropdown_filter', parentBody).css('display', 'none');
            });
        });
    </script>
<?php endif; ?>



