<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if (!$block->isContentMode() || $block->isMixedMode()): ?>
    <div id="layer-product-list">
        <div class="loading_overlay"></div>
        <?php echo $block->getProductListHtml() ?>
    </div>
<?php endif; ?>
