<?php

// @codingStandardsIgnoreFile
$transactions = $block->getTransaction();
$transactionArr = array();
if(count($transactions)){
    $transactionArr = array($block->getReceivedTransaction(), $block->getRemainTransaction());
}
?>
<?php echo $block->getChildHtml('info');?>
<div class="right_col" role="main">
    <div class="">
        <div>
            <div>
                <h3>Transactions <small>Agreement between a buyer and a seller</small></h3>
            </div>
        </div>

        <div class="x_content">
            <div>
                <div class="row" style="text-align: center;">
                    <div class="col-md-4">
                        <canvas class="canvasDoughnut" height="110" width="110" style="margin: 5px 10px 10px 0"></canvas>
                        <h4 style="margin:0"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($block->getTotalTransaction(), true, false); ?></h4>
                    </div>
                    <div class="col-md-4">
                        <canvas class="canvasDoughnut" height="110" width="110" style="margin: 5px 10px 10px 0"></canvas>
                        <h4 style="margin:0"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($block->getTotalTransaction(), true, false); ?></h4>
                    </div>
                    <div class="col-md-4">
                        <canvas class="canvasDoughnut" height="110" width="110" style="margin: 5px 10px 10px 0"></canvas>
                        <h4 style="margin:0"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($block->getTotalTransaction(), true, false); ?></h4>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Default Grid <small>Transactions</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Order #</th>
                                <th>Date</th>
                                <th>Transaction Amount</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if ($transactions && count($transactions)): ?>
                                <?php foreach ($transactions as $transaction): ?>
                                    <tr>
                                        <td><?php echo $transaction->getId();?></td>
                                        <td><?php echo $block->getOrderIncrement($transaction->getOrderId());?></td>
                                        <td><?php echo $transaction->getCreatedAt();?></td>
                                        <td><?php echo $this->getAmount($transaction->getAmount());?></td>
                                        <td>
                                            <a href="<?php echo $block->getViewUrl($transaction) ?>">
                                                <span><?php echo __('View') ?></span>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            </tbody>
                        </table>
                        <?php if ($block->getPagerHtml()): ?>
                            <?php echo $block->getPagerHtml();?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
$formData = [
    'transactionData' => $transactionArr
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);

?>

<script type="text/x-magento-init">
    {
        "*": {
            "chartJs" : {},
            "moment" : {},
            "admin_vendor": <?php /* @noEscape */ echo $serializedFormData; ?>
        }
    }
</script>
