<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
 
$helper = $this->helper('Netbase\Sun\Helper\Data');
$flag_config = $helper->getConfig('sun_settings/header/header_left_top_language');
?>

<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?> 
<?php $current_flag = $block->getStoreName();  ?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
			<?php if($flag_config == 1) { ?>
			<img src="<?php echo $block->getViewFileUrl('images/flags/'. $current_flag.'.jpg'); ?>" alt="<?php echo $current_flag; ?>" title="<?php echo $current_flag; ?>" />
			<?php } ?>
            <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <span><?php echo $block->escapeHtml($block->getStoreName()) ?> <i class="icon-angle-down"></i></span>
            </strong>
        </div>
        <ul>
            <?php foreach ($block->getStores() as $_lang): ?>
					<?php $flag = $block->escapeHtml($_lang->getName());?>
                    <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
						<?php if($flag_config == 1) { ?>
						<img src="<?php echo $block->getViewFileUrl('images/flags/'. $flag.'.jpg'); ?>" alt="<?php echo $flag; ?>" title="<?php echo $flag; ?>" />
						<?php } ?>
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                            <?php echo $block->escapeHtml($_lang->getName()) ?></a> 
                    </li> 
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
