<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$showWishlist = true;
$showCompare = true;
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_category_grid_config = $this->helper('Netbase\Sun\Helper\Data')->getConfig('sun_settings/category_grid');
$columns ='columns'.$_category_grid_config['columns'];
?>
<?php
	$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>

    <div class="tool-bar-top toolbar-category">
        <?php echo $block->getToolbarHtml() ?>    
    </div>
    
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?> <?php echo $columns ?>">
        <?php $iterator = 1; ?>
        <div class="row">
	        <ol class="products list items product-items">
	            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
	            <?php foreach ($_productCollection as $_product): ?>
	                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?> 
								 
								<?php      
									$originalPrice = $_product->getPrice();  //200 
									$specialPrice = $_product->getSpecialPrice();  
								?>   
						            <?php
									    $image = 'category_page_grid' or 'category_page_list';
									    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
									    $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(160)->getUrl();
									?>
						 			<div class="item-top">
										<?php if(($specialPrice)&&($specialPrice <= $originalPrice)){?>	
											<div class="sale">
												<span> 
													<?php
														$saleof= abs(($specialPrice/($originalPrice))*100-100);
														echo '- ';    
														print_r(floor($saleof));
														echo '%'; 
													?>									 
												</span> 
											</div>
										<?php } ?>
										<div class="product-item-info" data-container="product-grid">
							 			<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
											<img src="<?php echo $productImage; ?>" />
										</a>
										<?php if ($block->getMode() == 'grid') { ?>
											<div class="actions">
												<div class="quickview actions-all">
													<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
														->setData('pid', $_product->getId())
														->setTemplate("Cmsmart_Quickview::quickview.phtml")->toHtml();?>
												</div> 
												<div class="tocompare-div actions-all">
													<a href="#"
													   class="action tocompare"
													   title="<?php echo __('Add To Compare'); ?>"
													   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
													   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
													   role="button">
													   <i class="fa fa-refresh" aria-hidden="true"></i>
													</a>
												</div>
												<?php if ($showWishlist || $showCompare): ?>
													<?php
													$objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
													$objBlock = $objectManagerr->get('\Magento\CatalogWidget\Block\Product\ProductsList');
													?>
													<div class="actions-secondary actions-all" data-role="add-to-links">
														<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
															<a href="#"
															   data-post='<?php /* @escapeNotVerified */ echo $objBlock->getAddToWishlistParams($_product); ?>'
															   class="action towishlist" data-action="add-to-wishlist"
															   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
																<span><i class='icon-heart-1'></i></span>
															</a>
														<?php endif; ?> 
													</div>
												<?php endif; ?>  
											</div>
										<?php } ?>	
										</div>
		                            </div>
									<div class="product details product-item-details">
										<div class="inner-product">
											<?php if ($block->getMode() == 'grid') { ?>
												<a href="<?php echo $_product->getProductUrl() ?>" class="product-item-link">
													<?php echo $_product->getName(); ?>
												</a>  
												<?php $ratingSummary = $this->getRatingSummary($_product);  ?>
												<div class="product-reviews-summary">
												    <div class="rating-summary">
												        <span class="label"><span><?php /* @escapeNotVerified */ echo __('Rating') ?>:</span></span>
												        <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $ratingSummary; ?>%">
												            <span style="width:<?php /* @escapeNotVerified */ echo $ratingSummary ? $ratingSummary: '0'; ; ?>%"></span>
												        </div>
												    </div>
												</div> 
												<div class="price-home"> 
													<?php 
														 echo $block->getProductPrice($_product) 
													?>
												</div> 
												<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
													<?php if ($_product->isSaleable()): ?>
														<?php $postParams = $block->getAddToCartPostParams($_product); ?>
														<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey')?>
															<button type="submit"
																	title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																	class="action tocart primary ">
																<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
															</button>
														</form> 
													<?php else: ?>
														<?php if ($_product->getIsSalable()): ?>
															<div class="stock available">
															<span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
														<?php else: ?>
															<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
														<?php endif; ?>
													<?php endif; ?>
												</div>
											<?php } else { ?>
												<a href="<?php echo $_product->getProductUrl() ?>" class="product-item-link">
													<?php echo $_product->getName(); ?>
												</a>
												<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?> 
												<div class="price-home"> 
													<?php 
														 echo $block->getProductPrice($_product) 
													?>
												</div>  
											<?php } ?>
 							            </div>

							            <?php if ($showDescription):?>
			                                <div class="product description product-item-description">
			                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
			                                </div>
			                            <?php endif; ?> 
										<?php if ($block->getMode() == 'list') { ?>
											<div class="actions"> 
												<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
													<?php if ($_product->isSaleable()): ?>
														<?php $postParams = $block->getAddToCartPostParams($_product); ?>
														<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey')?>
															<button type="submit"
																	title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																	class="action tocart primary">
																	<i class="icon-cart"></i>
																<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
															</button>
														</form> 
													<?php else: ?>
														<?php if ($_product->getIsSalable()): ?>
															<div class="stock available">
															<span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
														<?php else: ?>
															<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
														<?php endif; ?>
													<?php endif; ?>
												</div>
												<div class="quickview">
													<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
														->setData('pid', $_product->getId())
														->setTemplate("Cmsmart_Quickview::quickview.phtml")->toHtml();?>
												</div>
												<div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
													<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
														<?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
													<?php endif; ?>
												</div>
											</div>
										<?php } ?>
							        </div>  
							    
					<?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
	            <?php endforeach; ?>
	        </ol>
        </div>
    </div>

    <div class="tool-bar-bottom">
        <?php echo $block->getToolbarHtml() ?>    
    </div>
    
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php if ($block->getMode() == 'grid'): ?>
    <script type="text/javascript">
        require([
            'jquery'        
        ], function ($) {
            $('.main .products.grid .product-items li.product-item:nth-child(2n)').addClass('nth-child-2n');
            $('.main .products.grid .product-items li.product-item:nth-child(2n+1)').addClass('nth-child-2np1');
            $('.main .products.grid .product-items li.product-item:nth-child(3n)').addClass('nth-child-3n');
            $('.main .products.grid .product-items li.product-item:nth-child(3n+1)').addClass('nth-child-3np1');
            $('.main .products.grid .product-items li.product-item:nth-child(4n)').addClass('nth-child-4n');
            $('.main .products.grid .product-items li.product-item:nth-child(4n+1)').addClass('nth-child-4np1');
            $('.main .products.grid .product-items li.product-item:nth-child(5n)').addClass('nth-child-5n');
            $('.main .products.grid .product-items li.product-item:nth-child(5n+1)').addClass('nth-child-5np1');
            $('.main .products.grid .product-items li.product-item:nth-child(6n)').addClass('nth-child-6n');
            $('.main .products.grid .product-items li.product-item:nth-child(6n+1)').addClass('nth-child-6np1');
            $('.main .products.grid .product-items li.product-item:nth-child(7n)').addClass('nth-child-7n');
            $('.main .products.grid .product-items li.product-item:nth-child(7n+1)').addClass('nth-child-7np1');
            $('.main .products.grid .product-items li.product-item:nth-child(8n)').addClass('nth-child-8n');
            $('.main .products.grid .product-items li.product-item:nth-child(8n+1)').addClass('nth-child-8np1');

        
        });
    </script>
<?php endif; ?>




