<div class="share">
	<span class="label-share">	
		<?php echo __('share:') ?>
	</span>
	<ul>   
		<li class="facebook"> 
			<a class="" href="https://www.facebook.com/sharer/sharer.php?u=" title="facebook"><i class="icon-facebook-2"></i></a>
		</li>
		<li class="twitter">
			<a class="" href="https://twitter.com/home?status=" title="twitter"><i class="icon-twitter"></i></a>
		</li>
		<li class="google"> 
			<a class="" href="https://plus.google.com/share?url=" title="google"><i class="icon-gplus"></i></a>
		</li> 
		<li class="linke"> 
			<a class="" href="https://www.linkedin.com/shareArticle?mini=true&url=&title=&summary=&source=" title="linkedin"><i class="icon-linkedin-2"></i></a>
		</li> 
		
		<li class="printer">
			<a class="" href="https://pinterest.com/pin/create/button/?url=&media=&description=" title="pinterest"><i class="icon-pinterest-1"></i></a>
		</li>
	</ul>
</div> 