<div class="tab-content">
	<div class="nb-productvideo-collateral-box collateral-box">
		<div id="nb-productvideo-player" class="nb-productvideo-player">
			<div id="uploadform-content" style="display: none;">
				<div>
					<div class="nb-productvideo-uploadform" id="for_1400">
						<div class="form-head">
							<h4>Upload your video</h4>
						</div>
					</div>
				</div>
			</div>
			<div id="player-content" style="display: block;">
				<iframe src="https://www.youtube.com/embed/NzBNhg0Rz0U?modestbranding=1" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0"></iframe>
			</div>
		</div>
		<div class="nb-productvideo-details">
			<div class="nb-productvideo-description" id="details-content">
				<a href="https://www.youtube.com/embed/NzBNhg0Rz0U?modestbranding=1" target="_blank">Android 2.01 on HTC Touch Diamond</a> &mdash; Jan 13, 2017
				
				<br>
			</div>
			<div class="nb-productvideo-rates" id="rate-content">
				<div class="rate-box" id="nb-rate-box" onmouseout="vidtest.mouseOut(this);">
					<div class="rate-selector">
						<a href="#" onmouseover="vidtest.mouseMove(1);" onclick="vidtest.mouseClick(1); return false;"></a>
						<a href="#" onmouseover="vidtest.mouseMove(2);" onclick="vidtest.mouseClick(2); return false;"></a>
						<a href="#" onmouseover="vidtest.mouseMove(3);" onclick="vidtest.mouseClick(3); return false;"></a>
						<a href="#" onmouseover="vidtest.mouseMove(4);" onclick="vidtest.mouseClick(4); return false;"></a>
						<a href="#" onmouseover="vidtest.mouseMove(5);" onclick="vidtest.mouseClick(5); return false;"></a>
					</div>
					<div class="rate" id="nb-rate-indicator" style="width: 52%;"></div>
				</div>
				<div class="notice" id="nb-rate-notice" style="display: none;">Thanks for voting</div>
				<div class="notice" id="nb-rate-loader">Voting...</div>
			</div>
		</div>
		<div class="nb-productvideo-scroll-box">
			<div class="nb-productvideo-scroll-panel">
				<div class="counter">
					<span>6 Videos</span>
				</div>
			</div>
			<div class="nb-productvideo-scroller">
				<div id="owl-example" class="owl-carousel owl-theme" style="opacity: 1; display: block;">
						<div class="nb-productvideo-videoitem">
							<div class="border">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">
								<img alt="thumbnail" src="https://i.ytimg.com/vi/H3a78dSrp3M/hqdefault.jpg" class="image120">
								</a>
							</div>
							<span class="nb-productvideo-video-time">
								<span>1:10</span>
							</span>
							<div class="title">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">HTC Touch Diamond zoom </a>
								<br>John Doe                                    
							</div>
						</div>
						
						
						<div class="nb-productvideo-videoitem">
							<div class="border">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">
								<img alt="thumbnail" src="https://i.ytimg.com/vi/H3a78dSrp3M/hqdefault.jpg" class="image120">
								</a>
							</div>
							<span class="nb-productvideo-video-time">
								<span>1:10</span>
							</span>
							<div class="title">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">HTC Touch Diamond zoom </a>
								<br>John Doe                                    
							</div>
						</div>
						
						
						<div class="nb-productvideo-videoitem">
							<div class="border">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">
								<img alt="thumbnail" src="https://i.ytimg.com/vi/H3a78dSrp3M/hqdefault.jpg" class="image120">
								</a>
							</div>
							<span class="nb-productvideo-video-time">
								<span>1:10</span>
							</span>
							<div class="title">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">HTC Touch Diamond zoom </a>
								<br>John Doe                                    
							</div>
						</div>					
						
						<div class="nb-productvideo-videoitem">
							<div class="border">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">
								<img alt="thumbnail" src="https://i.ytimg.com/vi/H3a78dSrp3M/hqdefault.jpg" class="image120">
								</a>
							</div>
							<span class="nb-productvideo-video-time">
								<span>1:10</span>
							</span>
							<div class="title">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">HTC Touch Diamond zoom </a>
								<br>John Doe                                    
							</div>
						</div>												
						
						<div class="nb-productvideo-videoitem">
							<div class="border">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">
								<img alt="thumbnail" src="https://i.ytimg.com/vi/H3a78dSrp3M/hqdefault.jpg" class="image120">
								</a>
							</div>
							<span class="nb-productvideo-video-time">
								<span>1:10</span>
							</span>
							<div class="title">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">HTC Touch Diamond zoom </a>
								<br>John Doe                                    
							</div>
						</div>					
						
						<div class="nb-productvideo-videoitem">
							<div class="border">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">
								<img alt="thumbnail" src="https://i.ytimg.com/vi/H3a78dSrp3M/hqdefault.jpg" class="image120">
								</a>
							</div>
							<span class="nb-productvideo-video-time">
								<span>1:10</span>
							</span>
							<div class="title">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">HTC Touch Diamond zoom </a>
								<br>John Doe                                    
							</div>
						</div>						
						
						<div class="nb-productvideo-videoitem">
							<div class="border">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">
								<img alt="thumbnail" src="https://i.ytimg.com/vi/H3a78dSrp3M/hqdefault.jpg" class="image120">
								</a>
							</div>
							<span class="nb-productvideo-video-time">
								<span>1:10</span>
							</span>
							<div class="title">
								<a href="#" onclick="vidtest.playVideo('H3a78dSrp3M'); return false;">HTC Touch Diamond zoom </a>
								<br>John Doe                                    
							</div>
						</div>
				
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    require([
    'jquery', 
	'owl_carousel'
    ], function($){
		jQuery(document).ready(function() {
			jQuery("#owl-example").owlCarousel({
				// Most important owl features
				items : 5,
				itemsCustom : false,
				itemsDesktop : [1199,4],
				itemsDesktopSmall : [980,3],
				itemsTablet: [768,2],
				itemsTabletSmall: false,
				itemsMobile : [479,1],
				singleItem : false,
				itemsScaleUp : false,

				// Navigation
				navigation : true,
				navigationText : ["&lt;","&gt;"],
				rewindNav : false,
				scrollPerPage : false,

				//Pagination
				pagination : true,
				paginationNumbers: true,

//              autoHeight : true,
			});
		});
	});
	
 </script>