<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
    <button type="button" data-role="all-tocart" title="<?php /* @escapeNotVerified */ echo __('Add All to Cart') ?>" class="action tocart">
        <span><i class="fa fa-cart-plus" aria-hidden="true"></i><?php /* @escapeNotVerified */ echo __(' ADD ALL TO CART') ?></span>
    </button>
<?php endif;?>
