<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php $_order = $block->getOrder() ?>
<?php $productIds = $block->getProductIds();?>
<div class="actions-toolbar">
    <a href="<?php /* @escapeNotVerified */ echo $block->getPrintAllInvoicesUrl($_order) ?>"
       target="_blank"
       class="action print">
        <span><?php /* @escapeNotVerified */ echo __('Print All Invoices') ?></span>
    </a>
</div>
<?php foreach ($_order->getInvoiceCollection() as $_invoice): ?>
    <?php $invoiceId = $_invoice->getId();?>
    <div id="marketplace-invoice">
        <div class="order-title">
            <strong><?php /* @escapeNotVerified */ echo __('Invoice #') ?><?php /* @escapeNotVerified */ echo $_invoice->getIncrementId(); ?></strong>
            <a href="<?php /* @escapeNotVerified */ echo $this->getUrl("marketplace/order/pdfinvoices/invoice_id/$invoiceId") ?>"
            onclick="this.target='_blank'"
            class="action pdfinvoice">
                <span><?php /* @escapeNotVerified */ echo __('Print PDF Invoice') ?></span>
            </a>
            <a href="<?php /* @escapeNotVerified */ echo $block->getPrintInvoiceUrl($_invoice) ?>"
            onclick="this.target='_blank'"
            class="action print">
                <span><?php /* @escapeNotVerified */ echo __('Print Invoice') ?></span>
            </a>
        </div>
        <div class="table-wrapper table-order-items invoice">
            <table class="data table table-order-items invoice" id="my-invoice-table-<?php /* @escapeNotVerified */ echo $_invoice->getId(); ?>">
                <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Items Invoiced') ?></caption>
                <thead>
                <tr>
                    <th class="col name"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
                    <th class="col sku"><?php /* @escapeNotVerified */ echo __('SKU') ?></th>
                    <th class="col price"><?php /* @escapeNotVerified */ echo __('Price') ?></th>
                    <th class="col qty"><?php /* @escapeNotVerified */ echo __('Qty Invoiced') ?></th>
                    <th class="col subtotal"><?php /* @escapeNotVerified */ echo __('Subtotal') ?></th>
                </tr>
                </thead>
                <?php $_items = $_invoice->getAllItems(); ?>
                <?php $_count = count($_items) ?>
                <?php foreach ($_items as $_item): ?>
                    <?php if(in_array($_item->getOrderItem()->getProductId(), $productIds)):?>
                        <?php if ($_item->getOrderItem()->getParentItem()) {
                            continue;
                        } ?>
                        <tbody>
                        <?php echo $block->getItemHtml($_item) ?>
                        </tbody>
                    <?php endif;?>
                <?php endforeach; ?>
                <tfoot>
                <?php echo $block->getInvoiceTotalsHtml($_invoice)?>
                </tfoot>
            </table>
        </div>
    </div>    
    <?php echo $block->getInvoiceCommentsHtml($_invoice)?>
<?php endforeach; ?>
<script>
    require(['jquery', 'jquery/ui'], function($){ 
        $("table.invoice:not(:has(>tbody>tr))").parent().parent().remove();
    });
</script>