var config = {
    map: {
        '*': {
            cmsmartTreeview: 'Cmsmart_Marketplace/js/treeview/jquery.treeview',
            productGallery:     'Cmsmart_Marketplace/js/product-gallery',
            baseImage:          'Cmsmart_Marketplace/catalog/base-image-uploader',
            newOptionDialog:  'Cmsmart_Marketplace/js/new-option-dialog',
            openOptionModal:  'Cmsmart_Marketplace/js/option-modal',
            newVideoDialog:  'Cmsmart_Marketplace/js/new-video-dialog',
            openVideoModal:  'Cmsmart_Marketplace/js/video-modal',
            productEditForm: 'Cmsmart_Marketplace/js/product-edit-form',
            sellerProfile: 'Cmsmart_Marketplace/js/seller-profile',
            sellerEditProfile: 'Cmsmart_Marketplace/js/seller-edit-profile',
            relatedProduct: 'Cmsmart_Marketplace/js/product/related-product',
            upsellProduct: 'Cmsmart_Marketplace/js/product/upsell-product',
            crosssellProduct: 'Cmsmart_Marketplace/js/product/crosssell-product',
            productAttribute: 'Cmsmart_Marketplace/catalog/product/attribute',
            productAttributes:  'Cmsmart_Marketplace/catalog/product-attributes',
            configurableAttribute:  'Cmsmart_Marketplace/catalog/product/configurable-attribute',
            notification : 'Cmsmart_Marketplace/js/notification',
            owlCarousel: 'Cmsmart_Marketplace/js/owl.carousel.min',
            vacationInfo: 'Cmsmart_Marketplace/js/vacation-info',
            textillate: 'Cmsmart_Marketplace/js/lib/textillate/jquery.textillate',
            timecircles: 'Cmsmart_Marketplace/js/lib/timecircles/TimeCircles',
            sellerLocator: 'Cmsmart_Marketplace/js/plugin/locator/locator',
            locator_init:'Cmsmart_Marketplace/js/plugin/locator/locator_init',
            locator_creator : 'Cmsmart_Marketplace/js/plugin/locator/locator_creator',
            locator_map : 'Cmsmart_Marketplace/js/plugin/locator/map',
            chartJs : 'Cmsmart_Marketplace/vendors/Chart.js/Chart.min',
            dateJs : 'Cmsmart_Marketplace/vendors/DateJS/build/date',
            bootstrap : 'Cmsmart_Marketplace/vendors/bootstrap/js/bootstrap.min',
            bootstrap_daterangepicker : 'Cmsmart_Marketplace/vendors/bootstrap-daterangepicker/daterangepicker',
            datatables : 'Cmsmart_Marketplace/vendors/datatables/jquery.dataTables.min',
            flot : 'Cmsmart_Marketplace/vendors/flot/jquery.flot',
            flotPie : 'Cmsmart_Marketplace/vendors/flot/jquery.flot',
            flotResize : 'Cmsmart_Marketplace/vendors/flot/jquery.flot.resize',
            flotStack : 'Cmsmart_Marketplace/vendors/flot/jquery.flot.stack',
            flotTime : 'Cmsmart_Marketplace/vendors/flot/jquery.flot.time',
            flotSpline : 'Cmsmart_Marketplace/vendors/flot-spline/js/jquery.flot.spline.min',
            flotCurvedlines : 'Cmsmart_Marketplace/vendors/flot.curvedlines/curvedLines',
            flotOrderbars : 'Cmsmart_Marketplace/vendors/flot.orderbars/jquery.flot.orderBars',
            sparkline : 'Cmsmart_Marketplace/vendors/jquery-sparkline/jquery.sparkline.min',
            moment : 'Cmsmart_Marketplace/vendors/moment/min/moment.min',
            admin_vendor : 'Cmsmart_Marketplace/build/js/admin_vendor.min'
        }
    },
    shim: {
        "newAttributeDialog": ["jquery"],
        "newVideoDialog": ["jquery"],
        "cmsmartTreeview": ["jquery"],
        "owlCarousel": ["jquery"],
        "textillate": ["jquery"],
        "timecircles": ["jquery"],
        "sellerLocator": ["jquery"],
        "localtor_init": ["jquery"],
        "localtor_creator": ["jquery"],
        "locator_map": ["jquery"],
        "googleMapNote": ["jquery"]
    }

};