<div id="delivery-date">
    <strong><?php echo __('Delivery Date') ?></strong>
    <span class="price"><?=$block->getDeliveryDate() ?></span>
</div>
<?php if($block->getComment()):?>
<div id="delivery-comment">
    <strong><?php echo __('Comment') ?>:</strong>
    <span class="price"><?=$block->getComment() ?></span>
</div>
<?php endif;?>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            var element1 = $('#delivery-date').detach();
            var element2 = $('#delivery-comment').detach();
            $('.order-shipping-method').append(element1).append(element2);
        }
    );
</script>